### ISSUE TITLE
Add support for custom errorformat

### ISSUE THREAD

**Issue by kminh** [janko-m/vim-test#106]
Hi, thanks for this useful plugin.

One thing that has been requested a lot is the ability to navigate to each test error using `:cn` or `:cp` (e.g. https://github.com/janko-m/vim-test/issues/14, https://github.com/janko-m/vim-test/issues/67). Although vim-dispatch does open the quickfix window after running a test runner, it doesn't allow us to navigate to each test error for most test runners, it just shows the quickfix window with the whole output of a test runner. This is expected because `errorformat` is not set correctly, but it makes this plugin less useful.

I think there should be a way to allow users to set their own `errorformat` for each runner before a test is run, and the errorformat should be reset to its previous value (before running the test) so that other commands can still run correctly (such as `:make`) because they might use a different `errorformat`.

My suggestion is to add a new autoload function that returns an `errorformat` to use. For example we can add the following to `autoload/test/php/phpunit.vim`:
```vim
function! test#php#phpunit#errorformat() abort
  return '%E%n)\ %m,%C%f:%l,%C%m,%C%.%#'
endfunction
```
And then use its returned value to set `errorformat` before each test is run. With the above I can get `:cn` and `:cp` to work flawlessly.

We can even go further and let users specify their own errorformats for each test runner, similar to how pattern options are set.

Thanks for any consideration.

**Comment by janko-m** [comment]
Thanks for letting me know that this is still a problem. I think we agree that for a quickfix with test errors which can be navigated with `:cn` or `:cp` is exactly what dispatch.vim is made for, so we just need to figure out how to add our errorformat to dispatch.vim.

Firstly, the reason why I'm not in favor of making something like `test#php#phptunit#errorformat()` work is because that would be specific only to the "dispatch" strategy. And I want all vim-test's code to be generic, not tied to a specific strategy.

Now, the solution. Dispatch.vim does set a proper errorformat for some runners, but for some it doesn't, how come? It actually gets the errorformat from a Vim "compiler". A compiler is just a Vim file which specifies which command and errorformat will be used if you type `:make` (once you previously ran `:compiler <name>`; see the Elixir's [ExUnit compiler](https://github.com/elixir-lang/vim-elixir/blob/master/compiler/exunit.vim) as an example).

And dispatch.vim does something really cool around this notion of compilers. Instead of having to manually set a compiler for a test file with vanilla Vim, dispatch.vim allows you to execute a shell command, and what it does is it searches through all compilers that Vim has in its load path (that includes compilers that ship with Vim distribution plus from any extra plugins), and checks if a subset of your command matches the `makeprg` from the compiler. If it does, it temporarily sets that compiler for that shell command, which applies the errorformat.

So all you have to do to apply the proper erroformat in your case is to create a `phpunit` compiler (which you would put under ~/.vim/compiler/phpunit.vim), which would look like this:

```vim
" ~/.vim/compiler/phpunit.vim
if exists("current_compiler")
  finish
endif
let current_compiler = "phpunit"

let s:cpo_save = &cpo
set cpo-=C
CompilerSet makeprg=phpunit
CompilerSet errorformat=%E%n)\ %m,%C%f:%l,%C%m,%C%.%#

let &cpo = s:cpo_save
unlet s:cpo_save
```

Now when Dispatch.vim is scanning compilers for a `phpunit --filter 'foo'` shell command, it will see the the `makeprg` value of "phpunit" is indeed a subset of your shell command, and should set this compiler for the command.

**Comment by janko-m** [comment]
Actually, I wasn't quite accurate. Dispatch.vim searches if a `makeprg` matches the "beginning" of your shell command. So a `phpunit foo_test.php` will be matched, but not e.g. `bin/phpunit foo_test.php` or `vendor/bin/phpunit foo_test.php`, which I understood are the executables that are usually used in a PHP project. Dispatch.vim has an option to ignore beginnings of the command, so setting something like this should work with test.vim:

```vim
let g:dispatch_compilers = {'./bin/phpunit': 'phpunit', './vendor/bin/phpunit': 'phpunit'}
```

**Comment by kminh** [comment]
I see, I was able to get it to work perfectly with your advice too. I guess this should go into vim-test's readme? Could be very useful for other users.

Anyway, thanks again for this awesome plugin. I would rate it one of the best vim plugins ever created!

**Comment by kminh** [comment]
Another thing to discuss: I figure not everyone wants to use dispatch for this purpose (I actually don't). The issue with `:Dispatch` is that it returns to vim immediately, which means you can't see how many tests have run, or see if you're running the right test (important when running a single test method). We can toggle the quickfix window  manually, but that's not really intuitive.

The most intuitive strategy IMO is the `make` strategy, you hit `<leader>t`, tests run with `makeprg` set to the test command, you then see success/errors immediately, and then press Enter to return to Vim, with the quickfix window filled with errors if any. If I remember correctly, there was a `make` strategy.

So it's still great if you could add `test#php#phptunit#errorformat()`. Although you said that you wanted vim-test to be generic, adding `errorformat()` looks pretty consistent with the whole plugin (custom file patterns, custom options, etc.)

Hope that makes sense.

**Comment by janko-m** [comment]
You're absolutely right, there should be a `make` strategy which is a wrapper around Vim's `:make`. You remember correctly that there was such a strategy before, but the logic was really complex because everything had to be reset afterwards, instead I could've just reused dispatch.vim's functions for finding the right compiler. After I figured out how powerful dispatch.vim is, I removed the strategy because I thought everybody would prefer asynchronous execution. I was wrong, exactly for the advantages you specified, even I use the default synchronous strategy 😃

So, I'm definitely in favour of adding the strategy. However, I would like that it works exactly like Dispatch.vim does in terms of finding the right compiler (and I would add documentation for this). Dispatch.vim actually has a way of running a simple `:make` (it does it when it cannot run with any other strategy, which can be forced by setting `g:dispatch_strategies` to `[]`), unfortunately it immediately terminates the screen after executing `:make`, which we don't want. Maybe I can ask Tim Pope about changing that or adding some option, otherwise I will reimplement what I need to.

> Anyway, thanks again for this awesome plugin. I would rate it one of the best vim plugins ever created!

Thank you for such kind words, I'm really happy it's works well for you (although I would at least put it after Tim Pope's plugins in terms of excellence 😉).

**Comment by kminh** [comment]
> So, I'm definitely in favour of adding the strategy. However, I would like that it works exactly like Dispatch.vim does in terms of finding the right compiler (and I would add documentation for this). 

That would be great. What I proposed was something I thought would be easiest to implement. I've just checked vim-dispatch's codes, look like there's no public methods that we can utilize to "clone" such functionality.

> unfortunately it immediately terminates the screen after executing :make, which we don't want. Maybe I can ask Tim Pope about changing that or adding some option, otherwise I will reimplement what I need to.

Maybe persuading him is even harder than implementing such feature yourself haha.

> Thank you for such kind words, I'm really happy it's works well for you (although I would at least put it after Tim Pope's plugins in terms of excellence).

You're right, but we don't need compare with god-like plugins.
