### ISSUE TITLE
Mocha tests failing with 'Bailout called.'

### ISSUE THREAD

**Issue by jrolfs** [janko-m/vim-test#116]
I have Ruby 2.2.1 installed with `rbenv` and am getting the following error on the Mocha spec.

I tried first with Ruby 2.2.3 and got the same failures. In both cases I had to install `bundler` as well, not sure if that should be required.

![failure](http://d.pr/i/1bn6O+)

**Comment by janko-m** [comment]
That's weird, I have no idea where the error is coming from. Whenever you run the tests, it always fails on the Mocha tests? Why did you have to install Bundler, didn't `gem install vim-flavor` work?

**Comment by jrolfs** [comment]
It looks like `vim-flavor` `require`'s `bundler/setup`, I get the following when I run it without bundler installed:
```
Jamie at Murbella in ~/Development/vim-test (master)
⤳ vim-flavor test spec                                                       ◼ (2.2.1) ⏎
/Users/Jamie/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- bundler/setup (LoadError)
        from /Users/Jamie/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /Users/Jamie/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/vim-flavor-2.2.1/lib/vim-flavor.rb:1:in `<top (required)>'
        from /Users/Jamie/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /Users/Jamie/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /Users/Jamie/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/vim-flavor-2.2.1/bin/vim-flavor:2:in `<top (required)>'
        from /Users/Jamie/.rbenv/versions/2.2.1/bin/vim-flavor:23:in `load'
        from /Users/Jamie/.rbenv/versions/2.2.1/bin/vim-flavor:23:in `<main>'
```

**Comment by jrolfs** [comment]
And, yes it's always on the Mocha spec.

**Comment by jrolfs** [comment]
https://github.com/kana/vim-flavor/blob/master/lib/vim-flavor.rb#L1 ... interesting as it isn't listed as a dependency in the gem-spec.

**Comment by janko-m** [comment]
Yes, gems should never require Bundler, that should only be done by the user of the gem, I will send a PR to remove that.

This "Bailout called" error doesn't come from vim-flavor or any of the dependencies (I searched their codebase), so I have no clue where it could be coming from. A short term solution is to try commenting out spec/mocha_spec.vim, and see if the tests pass.

A long term solution would be switching to a more reliable test runner. I've tried switching to [Vader.vim](https://github.com/junegunn/vader.vim), because it's a pure-VimScript test runner so it wouldn't require people to have Ruby nor any Ruby libraries installed. However, it turned out that it wasn't suitable for the kind of tests I have -- it's more for plugins for editing text -- and I couldn't get things to work for my test suite.

I recently saw [Vimrunner](https://github.com/AndrewRadev/vimrunner), which could be just what I need. It would still require Ruby, though, but I think the way that it works is way simpler and easier to debug. I've tried multiple times to understand how vim-flavor works, but it's beyond me.

**Comment by jrolfs** [comment]
I'll let you know if all the others pass. It's not that big of a deal, I was only trying to get the tests running because I'm planning on adding support for [AVA](https://github.com/avajs).

So long as a I don't run into a similar issue when writing specs for it, this shouldn't be an issue, so I wouldn't spend time trying to switch the runner just yet unless you have the time on your hands ;).

Anyways, thanks for vim-test, it really is great and I'll let you know if I run into anything.

**Comment by janko-m** [comment]
@jrolfs That would be amazing! My brother was recently totally mind blown by AVA :)

**Comment by janko-m** [comment]
I've got this error now when adding Rust's Cargo runner, when in the test I cd-ed into a fixtures directory, `spec/fixtures/cargo`, which I forgot to create. But this is strange, because `spec/fixtures/mocha` exists and is checked into version control, so I don't know how it happened to you. It must be related with what happened to me, that some folder doesn't exist.

I will close this for now because I think determined where the error is coming from.

**Comment by dingbat** [comment]
Just in case anyone else runs into this, or if it's useful for debugging somehow, I found a strange correlation when getting this error. If I had a certain test file just open in vim, I would consistently get the error, and as soon I closed the file, it would consistently pass (from outside of vim of course). Very weird, but it was consistent enough that I figured I'd post here and save someone else a possible headache.
