### ISSUE TITLE
Option to keep neovim terminal open after successful test run

### ISSUE THREAD

**Issue by kevinburkeshyp** [janko-m/vim-test#118]
If you run a test in the neovim terminal with vim-test and it passes, the terminal window quits immediately. It would be nice if you could choose to press Enter to dismiss the console output.

It looks like the relevant code is here:

```vimscript
function! test#strategy#neovim(cmd) abort
  let opts = {'suffix': ' # vim-test'}
  function! opts.on_exit(job_id, exit_code)
    if a:exit_code == 0
      call self.close_terminal()
    endif
  endfunction
  function! opts.close_terminal()
    if bufnr(self.suffix) != -1
      execute 'bdelete!' bufnr(self.suffix)
    end
  endfunction

  call opts.close_terminal()

  botright new
  call termopen(a:cmd . opts.suffix, opts)

  wincmd p
endfunction
```

Maybe another global var like `g:preserve_results_on_success` or something?

**Comment by kevinburkeshyp** [comment]
(Among other things I like to get visual confirmation that the correct test ran, look at how long it took, and see if there was any unnecessary console output)

**Comment by janko-m** [comment]
I think these are going to need to be two different strategies, because both of these strategies have advantages and disadvantages. I was hoping that for the use case you're describing the "basic" or "make" strategies would be enough, but their downside is that they're not asynchronous.

The neovim strategy previously worked in the way that you described, however, there were two problems that I didn't know how to solve properly.

First one is that closing the terminal window would switch focus to the window nearest to the terminal, not the window you were at when you ran the test (https://github.com/janko-m/vim-test/issues/98). When opening the teminal with a command, there *is* an `on_exit` hook, but it's run after the command finishes, not after the Terminal closes. I didn't find a way to control to which window is focused after user closes the terminal.

Second one is that I couldn't decide after the test finished whether to start insert mode in the terminal or not. If I *start* insert mode, user can just press any key to close the terminal, but they cannot move up the buffer (I didn't find a way to go back to normal mode from insert mode in the terminal). If I *don't start* insert mode, user can move in the buffer but they now need 2 keystrokes to close the buffer (which can get annoying if you're running tests often).

If someone knows how to solve these two issues, that would be great. Otherwise I'm not sure how worthwhile adding this strategy is.

**Comment by kevinburkeshyp** [comment]
> I was hoping that for the use case you're describing the "basic" or "make" strategies would be enough, but their downside is that they're not asynchronous.

I don't mind it being synchronous, but with neovim + the basic strategy, ANSI escape codes show up in the terminal as `[031m;` instead of having colors. I believe the neovim team is not planning on fixing that, instead asking people to use the terminal version. https://github.com/neovim/neovim/issues/2765

**Comment by janko-m** [comment]
@kevinburkeshyp In my recently compiled Neovim I don't have the ANSI escape codes, either because Neovim removes them or my test runner detects that the "terminal" doesn't support colors (probably the latter). But even if we could remove the ANSI codes, it probably still sucks not to have colors.

Know when I thought about it more, did you maybe try [Neoterm](https://github.com/kassio/neoterm)? Not the test runners part, just the controlling of the Neovim terminal. Vim-test supports this strategy, so you can try it out by adding the plugin and setting strategy to `neoterm`.

**Comment by dalizard** [comment]
@janko-m 
> I didn't find a way to go back to normal mode from insert mode in the terminal

I am not sure if you are looking for `<C-\><C-n>`?

**Comment by janko-m** [comment]
@dalizard Yes, this is what I was looking for!

There is also a `TermClose` event, which I could try to use for switching to the previous buffer. Ok, so it seems that I could get the behaviour that I want.

However, I'm curious whether it's worthwhile since [Neoterm](https://github.com/kassio/neoterm) already implements similar behaviour with a lot of flexibility and configuration, and test.vim supports Neoterm. I just don't want to be reimplementing something that already exists. Are there any disadvantages of using Neoterm?

A disadvantage that I've noticed is that Neoterm is reimplementing test.vim, which is a bit lame, and it seems that all this useful configuration for autofocusing, autoinserting and autoclosing is only taking effect if you run tests through Neoterm. However, it still seems that a lot of other configuration is generic, and Neovim itself looks pretty hackable, so maybe I could still implement what I want.

**Comment by dalizard** [comment]
@janko-m I used Neoterm some time ago but I wasn't quite happy with the way it worked. For example, it kept multiple terminals open and didn't close them when I thought it was appropriate to close them. There were few other small pieces, which I didn't find very intuitive either. Then I came across your project and I did the switch immediately. I haven't looked back. Thank you for your great work!

**Comment by janko-m** [comment]
@dalizard You're welcome!

After thinking about it more, I've realized that the current `neovim` strategy, with its no loss of focus and staying on errors, has exactly the behaviour of Dispatch.vim. So I think for that behaviour it's better to use a Neovim strategy for Dispatch.vim, which has already been done: https://github.com/radenling/vim-dispatch-neovim

So I will restore the behaviour of the `neovim` strategy to how it was before, plus returning to the correct buffer. Sorry for the trouble!

**Comment by dalizard** [comment]
@janko-m To be honest, I find this behaviour a bit odd. Specifically, I am referring to the _insert_ mode within the terminal after a failed test. I would say that most of the time, if not all the time, your next step would be exit the _insert_ mode, go to the implementation file and change something, and then run the test again. I'd rather have the cursor stay where it is (in the implementation file) and not move at all. This is, in my opinion, the most used case. I would suggest a setting(s), which would allow you to override this behaviour instead. But if you are doing TDD/BDD, not having to exit _insert_ mode or close terminal window, and get back to your implementation file or spec file is a huge benefit. We lose that after this change. Any thoughts? /cc @janko-m @kevinburkeshyp

**Comment by janko-m** [comment]
@dalizard That was the original behaviour of the `neovim` strategy, but I could find a way to make it configurable. That's what's I was hoping that Neoterm project would be, a good `:terminal` manager which you can configure in any way you like. I'm a bit reluctant to start adding strategy-specific configuration variables, I was always relying on the strategy itself being configurable, I think it would give test.vim too much responsibilities.

So, we have two options:

* introduce strategy-specific global variables to test.vim, or
* create a better Neoterm-like plugin, which does one-thing-and-one-thing-right, and add support for that plugin in test.vim

I'm currently more in favor of the second option.

**Comment by dalizard** [comment]
@janko-m I agree with you. The second option sounds more reasonable. I am also against too many responsibilities. Like I said, I tried neoterm, but it didn't have the same "smooth" experience as vim-test - it would not pick the correct runner in some cases, it would not pick pre-loaders if they are running (zeus for example), it would not clear the previous output of tests, sometimes it would not scroll to the last running test unless you manually clear the terminal, etc. etc. I haven't tried the plugin (neoterm) for some time now, but I'd rather use vim-test :)

**Comment by janko-m** [comment]
@dalizard By "using Neoterm" I meant to use it only for sending commands to the terminal, since it already has ability to reuse the existing terminal, autoclosing, autoinserting etc. Neoterm's support for *building* test commands is a completely separate responsibility, you can use it by calling `neoterm#test#run(...)`, but in our case we're using Test.vim to build the command, and use Neoterm just to run it. So Test.vim and Neoterm are actually additive, the Neoterm author could've just left building test commands to Test.vim 😃

I will study Neoterm more in depth, and see if I can address its limitations by contributing to the project. Otherwise I will probably create a new plugin, perhaps using Neoterm's [terminal-controling](https://github.com/kassio/neoterm/blob/e0576b850daa98385a0db0e8f572ea3ba89ad990/autoload/neoterm.term.vim) under the hood (anyone else is welcome to do it as well). I will open a new issue for that.
