### ISSUE TITLE
Clojure

### ISSUE THREAD

**Issue by donbonifacio** [janko-m/vim-test#12]
Hello,

What would you need to support clojure? How can I help you?
Usually, there isn't a command to run. A repl must be running and at this moment we have a vim plugin that sends code to the _remote_ repl and presents the result ([vim-fireplace](https://github.com/tpope/vim-fireplace)). This works great, but that run last test feature would be awesome. :)

**Comment by janko-m** [comment]
Yes, I would really like to support Clojure, but I found it a bit overwhelming at first, since I don't know Clojure at all :)

My idea was also to hook up to vim-fireplace, since it already has support for running tests. But I don't know how to implement it so it behaves the same way as the rest of the frameworks (most notably that it remembers the last test). I will try to dig into vim-fireplace code some more and see if I can work something out, it's just a bit difficult to read :)

**Comment by janko-m** [comment]
@donbonifacio I need your help:

1. Is it possible with vim-fireplace to run specific tests inside a file, and how can you do it? Can it run specific tests by name/regex (or line number)?
2. How does regular running tests look like? If you want to run the current file, do you simply call `:RunTests my_file.clj` or do you need something else? 
3. `:RunAllTests` accepts some additional arguments, do you know what do these arguments do if they're passed in? ([code](https://github.com/tpope/vim-fireplace/blob/master/plugin/fireplace.vim#L1504))

**Comment by janko-m** [comment]
Also, is there some naming convention that is used for test files? Either filename-wise or folder-wise, some way I can detect if a .clj file is a test file?

**Comment by donbonifacio** [comment]
Hey @janko-m,

I don't know if it can run a specific line number. Normally, I use it by sending to the repl a s-expression. For example:

```clojure
(deftest a
  (is (= 1 1)))
```
If I put the cursor on `is`, and press `cpp` it will evaluate all that expression. If I do it on `deftest` it will only send the function to the repl and won't run it.

To run all tests, I press `cpr` (reloads and runs all), or via a command: `:RunTests `.

`:RunAlltests` has the same parameters as `:RunTests`. I presume they're optional? I never use args.

Tests are usually on the `test/` folder. Sometimes end in `-test.clj`

Does this help?

**Comment by janko-m** [comment]
You said that you run all tests with `cpr`, which I see runs `:Require` in a .cljs file (ClojureScript, I presume?), otherwise runs `:RunTests`. By "all tests" you meant all tests in the current file? Can you `:RunTests` for a file that isn't the current buffer (e.g. `:RunTests another_file.clj`)?

So, when you run `cpp`, it runs the test the cursor is currently on (assuming you put the cursor in the right place)?

Yes, the arguments to `:RunTests` and `:RunAllTests` are optional, I just wanted to understand what they do, because this plugin forwards options from test.vim's commands, so I just wanted to make sure it will be correct. I'll just forward them, and we'll see :)

**Comment by janko-m** [comment]
Actually, I just realized we can't use `cpp`, because then it's not possible to implement the last test. What I need is that you help me figure out how to run commands which aren't dependent on where the cursor is currently. I presume it should be something like this:

* Nearest test: `:RunTests some_file.clj <options?>`
* File test: `:RunTests some_file.clj`
* Test suite: `:RunAllTests`

Do you perhaps know how to run tests this way?

Also, just to check if you maybe mispelled, do the test files sometimes end with `-test.clj` or `_test.clj`? Because I saw on [this guide](https://github.com/clojuredocs/guides/blob/master/articles/tutorials/vim_fireplace.md) that the example test file ended in `_test.clj`.

**Comment by janko-m** [comment]
Or maybe it would be better if I used `:Eval` coupled with `:Require!`. That the left hand side would roughly translate to the right hand side:

test.vim | fireplace.vim
---------- | -----------
`:TestNearest` | `:Require! | Eval (clojure.test/run-tests 'the-ns.the-test)`
`:TestFile` | `:Require! | Eval (clojure.test/run-tests 'the-ns)`
`:TestNearest` | `:Require! | Eval (clojure.test/run-all-tests)`

Could this work? The Clojure code above is probably wrong, but that would be the idea. From [this StackOverflow answer](http://stackoverflow.com/questions/24970853/run-one-clojure-test-not-all-tests-in-a-namespace-with-fixtures-from-the-rep) maybe for nearest test `clojure.test/test-vars` should be used?

**Comment by donbonifacio** [comment]
Hey,

Yes, it was a type. Normally a namespace like `some-namespace` will be on a filed like `some_namespace`. So, test files usually end with `_test.clj`, but that is just a convention.

I tried your examples, and they worked. :) 

Note for the nearest, I had to use it like:
`:Require! | Eval (clojure.test/test-vars [#'the-ns/testname])`

When the test fails, I get output. If it does not fail, I just get nil.

**Comment by janko-m** [comment]
Thank you for you feedback.

I realized using `:Eval` doesn't use Fireplace.vim's [internal test runner](https://github.com/tpope/vim-fireplace/blob/v1.0/plugin/fireplace.vim#L1424-L1440), so I managed to use it by partially reimplementing `:RunTests` and `:RunAllTests` (this way I could also add nearest test, which Fireplace.vim doesn't really support).

I have just one concern. Is it possible to reload *all* Clojure code, not just specific namespaces? I noticed that Fireplace.vim doesn't reload code on `:RunAllTests`, which means code could be unreloaded.

One minor bug in my implementation is that if a nearest test fails, and you fix it, and run the nearest test again, the quickfix will be cleared, but won't dissapear. This is because `test-vars` doesn't work the same as `run-tests` and `run-all-tests`, it doesn't return the metadata (e.g. `{:type :summary, :fail 1, :error 0, :pass 1, :test 2}`), instead it returns `nil`, so Fireplace.vim can't parse it correctly. I don't think Fireplace.vim can do anything about it, I think it should be fixed in Clojure itself. But anyways, it's a minor thing.

Let me know if something doesn't work.
