### ISSUE TITLE
Start Test Run Outside Test File

### ISSUE THREAD

**Issue by trisys3** [janko-m/vim-test#129]
Could we start the test run outside the test file, like i.e. in the file the test file is testing? For example, if I am running `karma` tests, I may have already created all my tests, and now I am writing the actual code. Alternatively, I am testing for regressions. Either way, I will not want to open the test file, or even switch to it, on each test, then run the test runner again, just to see that my test does, indeed, still pass. I would only want to switch if the test fails.

Another thing is that for a test runner like `jasmine` or `karma`, I do not actually want to run all the tests when I am writing the test file, except maybe to prove that the test *fails* and I need more code in the other file. I want to run the tests when I am writing the code in the *regular* file.

Right now, I have a `gulp` task set up to run all tests in the project at the start, then run all tests for a single file when that file or its test file changes. However, it is a pain to always be watching the terminal that has `gulp`. Using `syntastic` has been a boon and has saved me so much time, and if `vim-test` could do something similar, that would be amazing.

This seems similar to #115 but hopefully I provided enough of a reason to support it.

**Comment by janko-m** [comment]
I actually gave this a lot of thought in the beginnings of test.vim. As I understood, you would like that when you start Vim, you can immediately run the tests when you're positioned on a *regular* file. That is, that you don't need to give test.vim prior context, but you can just run the first test from a regular file.

The problem here is, how can test.vim determine what is the test file that corresponds to that regular file? Currently when you're positioned in a regular file, test.vim will simply run the last test. I suppose if you set up alternate files using [projectionist.vim](https://github.com/tpope/vim-projectionist), test.vim could pick that up and try to run tests for the alternate file. I remember trying that out, although I had some issues which I cannot remember now.

Let's assume this could be implemented (I would definitely like to give it another shot). Let's say that you ran a test file from a regular file, and then you switch to another regular file. If you then try to run tests there, what would be the correct behaviour, that test.vim runs the test file belonging to the new regular file, or the last test?

I'm still not sure how useful this feature is. Firstly, it would require setting up your project with projectionist.vim, so that it knows which test file belongs to which regular file. I don't see another way for test.vim to determine what you're asking for. But once you have projectionist.vim, you could just run `:A` - "mapping for running tests" - `:A` to run the corresponding test file, which is still really fast IMO.

**Comment by trisys3** [comment]
I was thinking of a lot of regexes. I actually started creating a plugin based on exactly this idea, [angulester](https://github.com/trisys3/angulester.vim), then when I found this plugin I (still worked on it out of stubbornness/pride until I) decided to try your plugin instead of finishing mine.

[projectionist](https://github.com/tpope/vim-projectionist) looks good, too, I'm going to take your advice and try it this week or next. If I like it enough, I will close this issue, but a doc update would be great, too.

**Comment by trisys3** [comment]
OK, I've been checking out [https://github.com/tpope/vim-projectionist](projectionist), and it looks cool. One problem, which the maintainer says he will tackle in version 1, is 2 alternate files for the same file, which would be a problem for me since we use `karma` and `protractor`, often for the same file, but other than that it's fine.

I'm going to close this issue. I still think a doc update explaining this situation better would be nice, but that could be another issue, if anything.

**Comment by janko-m** [comment]
@trisys3 Just following up that I managed to integrate with projectionist.vim, in https://github.com/janko-m/vim-test/commit/1edd7be495b76f1332a8d6b5c3bb1d2bc5aacd17.
