### ISSUE TITLE
nose2 support

### ISSUE THREAD

**Issue by furgerf** [janko-m/vim-test#138]
Hi, I'd like to use this great plugin for running nose2-tests but that doesn't seem to work. As far as I can see, nose2 requires test _names_ rather than test _files_ - to get that, I'd need to replace the path separator with dots and trim the file ending - eg. `test/bar-test.py` would become `test.bar-test`.

I don't see how I could modify the existing nose runner or create an extension where that would work, maybe you have an idea..? Thanks in advance!

**Comment by janko-m** [comment]
I think that just modifying [`test#python#nose#build_position()`](https://github.com/janko-m/vim-test/blob/master/autoload/test/python/nose.vim#L15) should work, where you return names instead of paths. So in `test#python#nose#executable()` you can detect nose2-tests and use that executable, and then in `test#python#nose#build_position()` you can make a conditional depending on whether that function returns a nose 1 or nose 2 executable. What do you think?
