### ISSUE TITLE
Elixir standalone test (using vim-dispatch)

### ISSUE THREAD

**Issue by patrickdavey** [janko-m/vim-test#149]
Hi there,

I came across vim-test recently and just love it! Paired with [vim-dispatch](https://github.com/tpope/vim-dispatch) it's amazing.

Anyway, I've been working through some [exercism](http://exercism.io/) tasks and running into a tiny issue with the tests. Basically if I have a test file like this:

```elixir
#simple_test.exs
ExUnit.start
ExUnit.configure trace: true

defmodule AcronymTest do
  use ExUnit.Case

  test "the truth" do
    assert 1 + 1 == 2
  end
end
```

Then the test runs, but the vim-dispatch pane stays open.

However... if I run the same test but embed it in part of a mix project, then it all runs perfectly (and no vim-dispatch window stays open).

I have made a [simple repo](https://github.com/patrickdavey/sample) outlining the issue here.

I'm honestly not sure whether the issue is here with [vim-test](https://github.com/janko-m/vim-test), or with [vim-dispatch](https://github.com/tpope/vim-dispatch) , or even if there's a conflict with [vim-elixir](https://github.com/elixir-lang/vim-elixir) if vim-elixir's errorformat is used by vim-test?

I don't really know vim-script that well, but if you could give me a pointer as to where the issue lies that'd be awesome!

Thanks again for the great plugin!!

**Comment by janko-m** [comment]
Thanks, I'm happy it's working well for you!

If the dispatch.vim quickfix stays open and the output isn't parsed and syntax highlighted, then the problem is the errorformat.

It might be that vim-elixir's `exunit` errorformat is correct, but that Vim is loading the `exunit` compiler which ships with Vim itself, although that's unlikely.

A more likely cause is that the `exunit` compiler isn't even getting loaded by Dispatch.vim. And I think that's your case, because Dispatch.vim activates the first compiler for which the test command matches [`CompilerSet`](https://github.com/elixir-lang/vim-elixir/blob/d3d964a8b1953e12cdadb77b3f255923f4873637/compiler/exunit.vim#L12). In this case, the `exunit` compiler will only get activated if your test command starts with `mix test`. However, if you're running exercisms, you're most likely not in a mix project, in which tests are run with simple `elixir simple_test.exs` command, so Dispatch.vim doesn't find the compiler that you want.

To fix this, Dispatch.vim provides [`g:dispatch_compilers`](https://github.com/tpope/vim-dispatch/blob/a54f2c5e18b8c2aad8c6f8ba474760e70fdaaca3/doc/dispatch.txt#L59) variable which you can modify, to tell Dispatch.vim that you want it to load the `exunit` compiler when the commands starts with `elixir`:

```rb
let g:dispatch_compilers = {'elixir': 'exunit'}
```

**Comment by patrickdavey** [comment]
You sir are a very helpful genius! That has fixed it perfectly.

Many thanks!

**Comment by jmgarnier** [comment]
Is there a similar solution to make it work with https://github.com/skywind3000/asyncrun.vim ?

I guess I could simply give a try to Dispatch
