### ISSUE TITLE
Vim 8 background job startegy

### ISSUE THREAD

**Issue by z0rc** [janko-m/vim-test#153]
Right now there is no strategy that supports background jobs added in Vim 8. Dispatch might get one eventually, but https://github.com/tpope/vim-dispatch/pull/193 looks stale and incomplete.

Anyway can you please add support of https://github.com/neomake/neomake? This runner looks like a great match for vim-test.

**Comment by janko-m** [comment]
@z0rc I think I would rather wait for Dispatch.vim to add the background jobs, because then it doesn't need to be reimplemented in two places.

As for Neomake, I suppose it wouldn't be difficult to add, and the implementation would probably be very similar to the `make` strategy (maybe even just replacing `:make` with `:Neomake`).

**Comment by codeinabox** [comment]
Is this something you'd like someone to submit a PR for?

**Comment by blueyed** [comment]
According to https://github.com/neomake/neomake/issues/1138 @markwoodhall has done it using Neomake.

As for myself, I am using vim-test with vim-dispatch-neovim currently (using these changes: https://github.com/radenling/vim-dispatch-neovim/pull/11).

**Comment by markwoodhall** [comment]
I've been working on a PR for a dotnet core test runner and as part of that was looking at using Neomake too. I'm not sure what I've done is particularly robust or finished at the moment, but I've been using it heavily this week. I'm happy to make any improvements that would be needed to make sure a Neomake strategy is reliable and works well. 

https://github.com/markwoodhall/vim-test/commit/b2cb6c2b71324a46078ed691d57b2b4e34ca6e04#diff-52fe4cbf4297c73b5a08849fdfa5eb1c

**Comment by janko-m** [comment]
@markwoodhall That's great, yes, it would be great if you could submit PRs for both dotnet runner and Neomake strategy. However, it seems that the current Neomake strategy just uses the `errorformat` that has already been set, right? In that case you always need to remember to execute the `:compiler` command when you turn on Vim in your project. I mean, I guess that isn't so bad, the tests would still execute, the only thing is that the quickfix list with test errors wouldn't be properly formatted and linked with an invalid `errorformat`.

In `test#strategy#make` handled that by invoking Dispatch.vim to find the right compiler for the given test command, and then executing that compiler to set the `errorformat` before the test command is executed. Basically I'm doing the same logic that Dispatch.vim internally does, just running `:make` instead of `:Make`. The advantage of that approach is that you don't need to remember to run the compiler before running your tests. The disadvantage is that you need to have Dispatch.vim installed as well. That's why I like the idea of Dispatch.vim having a strategy for Vim 8 background jobs.

But it's definitely possible to integrate Neomake, perhaps we could do the `dispatch#compiler_for_program` + temporary `errorformat` setting logic be executed only when Dispatch.vim is installed, otherwise just use whichever `errorformat` is set at the moment, like it's currently in your fork (and document that difference in behaviour).

**Comment by markwoodhall** [comment]
I will look to see if I can do something similar to the make strategy, where manual switching of the compiler is not needed. At the moment, I just have bindings for running each of the `:Test*` commands where the compiler is set correctly for what I'm doing. Which is annoying.

**Comment by codeinabox** [comment]
Closing this as PR has been merged in
