### ISSUE TITLE
request: 'silent' option

### ISSUE THREAD

**Issue by Alok** [janko-m/vim-test#164]
If the tests run successfully, it should be enough to just `echomsg "tests passed"`  or something rather than popping up a terminal, if the user sets the variable `g:test_silent_mode` or something.

**Comment by janko-m** [comment]
There is a similar issue open already, for showing a status when tests are running and passed, and opening the output only when they haven't, so I'll close this so that we can move the discussion there.

Btw, did you try using Dispatch.vim with the `dispatch` strategy? It seems to have exactly the behaviour as you described.
