### ISSUE TITLE
Too early compiler choice

### ISSUE THREAD

**Issue by przepompownia** [janko-m/vim-test#166]
With the below configuration 
```
" vim-test
let test#strategy = 'dispatch'

" vim-dispatch
let g:dispatch_compilers = {}
let g:dispatch_compilers.phpunit = 'phpunit2'
```
when I run, for example, `:TestNearest`, then `:Dispatch` gets `./vendor/bin/phpunit` into the first argument so `phpunit` compiler is ignored.

Although I found a workaround by set this argument manually
```
let test#php#phpunit#executable = 'phpunit'
```
I think that `test#php#phpunit#executable()` first should get the proper value from the compiler definition if that exist and if it make sense. It seems that searching the executable should be the responsibility of a particular _compiler_. 

Maybe this issue is more generic - not specific for `phpunit` and independent of `vim-dispatch`.

**Comment by janko-m** [comment]
The thing is that test.vim isn't generally related to Vim compilers. You can use a strategy that uses compilers under the hood (dispatch.vim), or a strategy which doesn't use them at all.

The reason why test.vim cannot utilize compilers is because: (a) it would have to re-implement searching trough compiler (because it cannot rely on dispatch.vim being installed), and (b) even if it did, using the command declared by the compiler isn't necessarily what users want to be run.

For example, I'm assuming that running `phpunit` isn't equivalent to running `./vendor/bin/phpunit`. If test.vim would choose the compiler command, users wouldn't be able to choose to run `./vendor/bin/phpunit` and still use the `phpunit2` compiler.

However, you can still configure dispatch.vim to use the `phpunit2` compiler without changing anything in test.vim. The `g:dispatch_compilers` dictionary has a double functionality: in addition to the dictionary value being a compiler name, it can also be a blank string, and then dispatch.vim will treat the key as a prefix that should be subtracted, and continue the compiler lookup without that prefix.

In your case you want to ignore `./vendor/bin/` from the command, so you can specify:

```vim
let g:dispatch_compilers = {}
let g:dispatch_compilers['./vendor/bin/'] = ''
let g:dispatch_compilers['phpunit'] = 'phpunit2'
```

Then `./vendor/bin/phpunit ...` command should be transformed into `phpunit ...`, which should then activate the `phpunit2` compiler.
