### ISSUE TITLE
Determining runner when test files have near identical syntax?

### ISSUE THREAD

**Issue by codeinabox** [janko-m/vim-test#177]
Is there an established way to determine the runner when test files have near identical syntax? Was considering creating a PR to add support for [Kahlan](https://github.com/kahlan/kahlan) and [Peridot](https://github.com/peridot-php/peridot).

These both use the extension of .spec.php and have very similar syntax. Only thing I can think of is check for the presence of the binary or grep composer.json to see if it's in there. Thoughts?

**Comment by janko-m** [comment]
Yeah, the same thing is bugging me as well, there is no established way yet. The JavaScript and Python runners suffer from the same problem, though for JavaScript you can at least check in `node_modules/` and `package.json`.

If `composer.json` is where you declare dependencies, then looking in it definitely sounds like a good idea. Though I guess not every PHP project uses a `composer.json`, right?

**Comment by codeinabox** [comment]
You'd be hard pressed to find a recent PHP project that doesn't use composer

**Comment by codeinabox** [comment]
I am not such an expert in Viml. How can I check if a string appears in composer.json and store the result as a boolean or count?

**Comment by janko-m** [comment]
Take a look at [`s:rails_version()`](https://github.com/janko-m/vim-test/blob/453db3d6dce641f91c66731aad971530729ca172/autoload/test/ruby/rails.vim#L39-L55), where I check Gemfile.lock (like a Ruby alternative for composer.json) for Rails and extract the version. Basically the method is `readfile()` which returns an array of lines, and then you can iterate over those lines and use `matchstr()`, which returns either the matched string or `0` (since Vim has a different regex behaviour by default, I prefer to add `\v` at the beginning which makes it a regular POSIX regex).

**Comment by codeinabox** [comment]
I decided the best and simplest solution for my PR #178 was just to check for the presence of the runner executable.
