### ISSUE TITLE
Setting task runner doesn't work with javascript

### ISSUE THREAD

**Issue by lan-nguyen91** [janko-m/vim-test#187]
this is what I have in my .vimrc

```
let test#strategy="basic"
let test#javascript#minitest#file_pattern=".spec\.js"
let test#javascript#runner="jasmine"
let g:test#runner_commands = ['jasmine']
```

I tried this too 
```
let test#javascript#runner="Jasmine"
let g:test#javascript#rspec#executable = 'Jasmine rspec'
```

The test ran, but it ran `mocha` as a runner, not sure what I did wrong.
I tried to capitalize letter `J` too, nothing works. I am using Neovim, and nvm, not sure if those two caught problems. 

The command that it prints is 
`:!node_modules/.bin/mocha test/controllers/client.spec.js` 

Can someone help,

Thanks.

**Comment by janko-m** [comment]
@lan-nguyen91 Not all test runners implement `test#{language}#runner` detection, there is an open ticket for generalizing this so that it automatically works with any test runner: https://github.com/janko-m/vim-test/issues/185

**Comment by janko-m** [comment]
@lan-nguyen91 As a temporary workaround you can try to set `test#javascript#mocha#file_pattern` to something that definitely won't match your test files, so that Mocha is skipped.

```vim
let test#javascript#mocha#file_pattern = 'mocha'
```

This should work unless there is some other JS runner after Mocha that will get detected by the same pattern.

We are also planning to modify all JavaScript test runners to only be activated if the corresponding Node package is declared in `package.json` (with the option to still manually set it via `test#javascript#runner` of course).

**Comment by lan-nguyen91** [comment]
I remove the array of options in you vim file, restricting to jasmine only for now. But looking forward to your update mentioned above. This is very helpful, thanks a lot! 👍

**Comment by codeinabox** [comment]
I could raise a PR to help with the detection. @janko-m are we thinking the package.json strategy?

**Comment by janko-m** [comment]
@codeinabox Yes, I think that neither of the JavaScript test runners should be activated if they are not listed in `package.json`. In addition to that, we should also do https://github.com/janko-m/vim-test/issues/185, so that people can select a runner even if it's not listed in `package.json`. That would be global (in `autoload/test.vim`), and would need be careful not to break anything.

**Comment by codeinabox** [comment]
What about yarn or as a first step should we just get it working for package.json?
