### ISSUE TITLE
How to change the test framework

### ISSUE THREAD

**Issue by mjacobus** [janko-m/vim-test#196]
Hi there

This is actually a question. Sorry to use an issue to ask it.

I am failing to change the testing framework.

I have a path/bar_spec.js and I try to use jest instead of jasmine.

I tried: 

```viml
let g:test#javascript#jest#file_pattern = '\v^.*spec\.(js|jsx|coffee)$'
```

Also, in some projects I need to run tests with `npm run test`. Is it possible to use this script?

**Comment by codeinabox** [comment]
Is your test runner listed as a dependency in your package.json? We have a PR #188 that detects based on that if you want to try that branch before it's merged.

**Comment by mjacobus** [comment]
In one of the cases it is listed in the package.json file. In the other case it is not. In another case it is, but the  package.json is inside `project_root/frontend/package.json`.

**Comment by codeinabox** [comment]
Does the latter project have multiple package.json files?

**Comment by mjacobus** [comment]
No.

**Comment by codeinabox** [comment]
If you could try changing to the branch in the PR and test it against the projects where package.json is in the project root that would be very helpful.

**Comment by janko-m** [comment]
@mjacobus There is https://github.com/janko-m/vim-test/issues/185 open for allowing you to manually select the test runner with a variable if test.vim doesn't detect it correctly, but I haven't found the time to get to it yet. This still doesn't mean that we shouldn't improve the detection in https://github.com/janko-m/vim-test/pull/188, I just wanted to provide a means to manually selecting the test runner so that it's not a blocker.

> Also, in some projects I need to run tests with `npm run test`. Is it possible to use this script?

This has been asked before, but I'm still not convinced that it would be a good idea to add something like this to test.vim. Firstly, this behaviour doesn't really fit in an new test runner, because there is no file pattern you can use (since you don't know which testing framework `npm run test` uses). Secondly, it wouldn't have the ability to run file tests or nearest tests, because it wouldn't know what arguments to pass for filtering (since it's a custom script).

What are the advantages of using `npm run test` over using the test runner directly? If there are advantages, how would you like it to work with test.vim (taking into consideration the previous paragraph)?

**Comment by codeinabox** [comment]
@mjacobus the package.json based detection is now merged into master though currently only supports the file in the project root directory. Sub-directory support is an enhancement saved for another time.
