### ISSUE TITLE
pipe vim-test commands output into another vim function using test strategy

### ISSUE THREAD

**Issue by myimages** [janko-m/vim-test#197]
Hi, I am very well aware of the other 2 issues that asks for vim-makegreen integration. 
however both of these provided strategies in those example call makegreen directly which makes the whole testsuite run (the equivalent of `:TestSuite` ) 
even if I ran `:TestFile` , the test strategy calls MakeGreen Directly like so 
` call MakeGreen(join(split(a:cmd)[1:]))`

The right strategy should be like this in vim's Ex mode:
`:TestFile | MakeGreen()`

so what I am having a hard time with is trying to translate the same Ex command into  a test strategy , and vim-test is very flexible in terms of where I would like those to be applied and to what file types etc which is excellent.

is this possible ?

I asked this question at [SO](https://stackoverflow.com/questions/44542827/how-to-pipe-a-shell-command-output-into-a-vim-function/44543301)

maybe a little example needs to be added to the docs and I would be more happy to do this If I figure out how to make the above strategy work.

**Comment by codeinabox** [comment]
Could you please link to the two aforementioned issues and I'll see what advice I can offer.

Is your desired outcome to use vim-makegreen to indicate if either TestFile or TestSuite passed?

**Comment by myimages** [comment]
Thanks for the quick reply.
here is the two comments and one of them is a strategy that I pasted the relevant code from.
[14](https://github.com/janko-m/vim-test/issues/14#issuecomment-160794118)
[104](https://github.com/janko-m/vim-test/issues/104#issuecomment-207514295)

the desired output will be whatever vim-test command I ran , be it `:TestFile`  `:TestNearest` etc , will get its output piped into a `MakeGreen()` function like `:TestNearest | MakeGreen()`.

with the linked example above, make green gets called inside a vim test strategy directly. (while it should just take whatever output vim-test gives it and process it)

so lets say I called `TestNearest` using the above linked strategy.  the expected behavior will be running the nearest test, but this does not happen (not a vim-test problem its the strategy function problem because vim-test will do whatever you want it to do).

instead it will call MakeGreen() first (which will run the whole test suite no matter what command you ask it to run) , then `a:cmd`  which will be `TestNearest`.

so given this vim Ex command `:TestNearest | MakeGreen()`

how could this be translated into a vim-test strategy ?

I apologize if I didn't know how to explain the issue I am having with vim script.

**Comment by codeinabox** [comment]
I am not familiar with MakeGreen and I don't think creating a strategy to send it the the test runner comments would be that difficult, for reference I'd look at the make strategy.

However according to the [documentation it requires an errorformat](https://github.com/reinh/vim-makegreen/blob/master/doc/makegreen.txt#L87) to determine whether it is red or green.

**Comment by myimages** [comment]
Error format is set and everything works as expected only if called like so 

:TestFile | MakeGreen()

here is a screen of the output
<img width="615" alt="screen shot 2017-06-14 at 4 24 02 pm" src="https://user-images.githubusercontent.com/23110352/27158881-44f42ecc-511e-11e7-9799-13f7f90958b8.png">

but I can't make this work as test strategy , see the below function definition of what I am trying to achieve.

```
function MakeGreenStrategy(cmd) abort
    execute '!' .a:cmd | MakeGreen()
endfunction
let g:test#custom_strategies = {'makegreen': function('MakeGreenStrategy')}
let g:test#strategy = 'makegreen'

```

a feature that is related to vim-test strategy and that would be very nice to have is something like 
`let g:test#use_make_green = true`
which will make the output look like the above if make-green is installed.

**Comment by codeinabox** [comment]
I think the issue is that MakeGreen don't accept arguments or piping like that. According to the documentation https://github.com/reinh/vim-makegreen/blob/master/doc/makegreen.txt you need to use `compiler` but wouldn't that require creating compiler settings for each test runner?

**Comment by myimages** [comment]
I am trying to understand how `makegreen` worked in the examples above which seems false positive because it did not read any error format , therefore , it marked it as green. 

I also have two other plugins installed which might have set those values to the wrong format , vim-ruby , and vim-rails.

both sets the compiler to `rubyunit` which is what makes green needs , I still need to look into makeprg and errorformat and I don't mind putting those settings in as long as it will work with vim-test in a strategy function.

and vim-test also sets the compiler at some level but I don't know how it works yet.


thanks for trying to help.

**Comment by janko-m** [comment]
@myimages Thank you for the thorough explanation! So, we just need to figure out how to make a strategy does the equivalent of

```
:TestFile | MakeGreen()
```

First, notice that `|` in VimScript doesn't mean "piping", it's just a way how to separate two commands. And there doesn't seem to be a way in VimScript to run a command like `:!<cmd> | MakeGreen`, there is a paragraph about it in `:help :!`. But since it's just running two commands one after the other, this should achieve the equivalent behaviour:

```vim
function MakeGreenStrategy(cmd) abort
    execute '!' .a:cmd
    call MakeGreen()
endfunction
let g:test#custom_strategies = {'makegreen': function('MakeGreenStrategy')}
let g:test#strategy = 'makegreen'
```

However, the `MakeGreen()` function doesn't capture the output of a previous command (nor it can), so this should be the same as just running `call MakeGreen()`.

> however both of these provided strategies in those example call makegreen directly which makes the whole testsuite run (the equivalent of :TestSuite ) even if I ran :TestFile , the test strategy calls MakeGreen Directly like so call MakeGreen(join(split(a:cmd)[1:]))

Ah, yes, I see what's the problem. This would work for commands like `rspec foo.rb`, but wouldn't work for commands like `bundle exec rspec foo.rb`. The issue is that, since `a:cmd` is a single string, there is no way for the strategy to know what is the "executable", and what are the CLI arguments.

However, there is an alternative. We can set `l:makeprg` to the full command, and run `MakeGreen()` without arguments, which will run `:make` without arguments, which executes whatever is in `l:makeprg`. It would definitely ideal to create a `makegreen` strategy, I will work on that.

> a feature that is related to vim-test and that would be very nice to have is something like `let g:test#use_make_green = true` which will make the output look like the above if make-green is installed and avoid using any test strategies.(given that the example above can be put into a strategy)

I would prefer if we make a new `makegreen` strategy instead of having `g:test#use_make_green = true`, because `MakeGreen()` works with only one way of executing the test command – it uses `:make` under-the-hood. So it wouldn't even be right that the `basic` strategy handles this option, it would only make sense that the `:make` strategy detects this option. But since that's an implementation detail of `MakeGreen()` (that it executes `:make`), I would prefer that we make new strategy for it (and we can then add it to `test.vim`).

> According to the documentation https://github.com/reinh/vim-makegreen/blob/master/doc/makegreen.txt you need to use compiler but wouldn't that require creating compiler settings for each test runner?

@codeinabox Yes, `MakeGreen()` runs `:make` under the hood, so it expects the compiler to be set. I agree it's definitely the responsibility of the user to create the appropriate compiler if it doesn't exist before, *and* to activate it before running `MakeGreen()` (or `:TestSomething` which would run `MakeGreen()`). But we can do the latter (activating the correct compiler) for the user has the Dispatch.vim plugin, because Dispatch.vim has helper function to find the correct compiler from the command, we are already doing that in the `make` and `neomake` strategies.

**Comment by janko-m** [comment]
@myimages I added the `MakeGreen` strategy, which automatically sets the correct compiler if Dispatch.vim is available. Could you test whether it works correctly?

**Comment by myimages** [comment]
@janko-m I apologize for the late reply , too many GH notification so , I missed that one. 

I appreciate taking the time to read, explain , and adding this feature.

I tested it , works as expected !  ( ruby ) 

Thanks for your efforts making and maintaining this plugin.
