### ISSUE TITLE
Alternative test runner commands

### ISSUE THREAD

**Issue by bradurani** [janko-m/vim-test#198]
In Elixir I find myself wanting to sometimes run:
`mix test`
and sometimes when I want to use bindings and don't mind that it leaves the session running:
`iex -S mix test`
Is there an easy way to set 2 separate  mappings?

**Comment by janko-m** [comment]
Not at the moment. Looking at the ExUnit runner, it wouldn't be easy to add support for that to the current ExUnit runner, because the `executable()` function doesn't currently accept any arguments, so we cannot pass an option that would change the executable (and doing so would break backwards compatibility for `executable()` functions of other runners that aren't part of test.vim).

I would recommend defining a transformation that detects an option, e.g. `--interactive`:

```vim
function! ElixirTransform(cmd) abort
  if matchstr(a:cmd, '\v^mix test.*--interactive')
    return substitute('iex -S ' . a:cmd, '--interactive', '', '')
  else
    return a:cmd
  end
endfunction

let g:test#custom_transformations = {'elixir': function('ElixirTransform')}
let g:test#transformation = 'elixir'
```

Now calling just `:TestSuite` would run `mix test`, while `:TestSuite --interactive` would run `iex -S mix test`, and you can map `:TestSuite --interactive` to another mapping.

**Comment by bradurani** [comment]
Perfect. Thanks!

**Comment by waiting-for-dev** [comment]
Thanks for the help here. There's a small bug in the snippet, though. `matchstr` will return an empty string when `--interactive` is not found, so the statement will still evaluate to a truthy value. Therefore, we need to check against the return value:

```vim
  if matchstr(a:cmd, '\v^mix test.*--interactive') != ''
```
