### ISSUE TITLE
After running tests, some texts are not getting displayed well.

### ISSUE THREAD

**Issue by mechanicles** [janko-m/vim-test#20]
I'm using tpope's `vim-dispatch` plugin as well. But after running the tests, some texts are not getting displayed properly. 

http://take.ms/wdjuO

Am I missing some setting?

**Comment by janko-m** [comment]
That's weird. You're using colored Minitest output, that is requiring `minitest/pride`, right? Those look like Terminal escape codes for colors, which Dispatch.vim is supposed to strip.

Have you tried upgrading to the latest version of Dispatch.vim? And also be sure to use the latest version of Test.vim. Because all I'm doing is calling the `rake test` command with `:Dispatch`.

**Comment by janko-m** [comment]
Open an issue on Dispatch.vim if you're still having problems, Test.vim shouldn't be the cause of this.
