### ISSUE TITLE
Show the tests output in fullscreen in neovim

### ISSUE THREAD

**Issue by skamsie** [janko-m/vim-test#203]
I have used this plugin with vim and it worked as I wanted out of the box. When I was browsing a test file and used any of the commands `TestFile`, `TestNearest`, etc I got the test output in a new window (which looks like it is actually the terminal). I really liked this, since once the tests are over I can freely scroll through the output.

Now, since I started using neovim, the output is always in a horizontal split screen, which I do not like. I have tried the various 'strategies' but none of them bring back the vim behaviour.

Any ideas how to do it?

Thanks

**Comment by codeinabox** [comment]
Have you tried the following?

```viml
let test#strategy = "basic"
```

**Comment by skamsie** [comment]
Yes, I have tried all strategies. "basic" looks like this for me, so even smaller than whatever the default is:

<img width="1280" alt="screen shot 2017-07-27 at 15 08 26" src="https://user-images.githubusercontent.com/7014744/28671569-7a0c0b1c-72dd-11e7-91f1-b42ffd514d0d.png">

**Comment by codeinabox** [comment]
Odd as for Vim the default strategy is `basic` https://github.com/janko-m/vim-test/blob/4f5e175894ce1131437000d4ee5ed256261056ae/autoload/test.vim#L81

**Comment by codeinabox** [comment]
Well Vim defaults to the `basic` strategy but Neovim defaults to `neovim`. If you add the following line to your .vimrc it should force Neovim to use behave the same.

```viml
let test#strategy = "basic"
```

**Comment by janko-m** [comment]
The issue is that on Neovim executing `:!<command>` (which is what the `basic` strategy does) doesn't have the same behaviour as on Vim -- it doesn't switch to an alternate screen. It's possible this feature was removed from Neovim, because you could probably achieve the same thing with Neovim's terminal.

I actually think this is the default behaviour of the `:terminal` command. The reason why `neovim` strategy doesn't have that behaviour is because I wrote it to open a split window instead. But I think it would be good to modify the `basic` strategy to execute `:terminal` when on Neovim, and make that the default strategy on Neovim (currently it's `neovim` because it's better on Neovim than the current `basic` strategy) as it already is the default for Vim.

**Comment by codeinabox** [comment]
Though Vim now also supports `:terminal` https://github.com/vim/vim/commit/e4f25e4a8db2c8a8a71a4ba2a68540b3ab341e42

**Comment by janko-m** [comment]
Test.vim on Neovim will now also use the `basic` strategy by default, which will on Neovim open a `:terminal` in a new tab, making it full-screen. The `neovim` strategy remains the same.
