### ISSUE TITLE
TestVisit toggle back to where you come from

### ISSUE THREAD

**Issue by lee-kagiso** [janko-m/vim-test#23]
Right now TestVisit is a pretty awesome feature to get from your code to the last test, but what happens if I want to get back to my code again (Ctrl ^ but this is a PITA), is it possible to easily add a toggle feature?

models.py :TestVist => test_models.py
test_models.py :TestVisit => models.py?

**Comment by janko-m** [comment]
I'm glad you like the `:TestVisit` command :). You can just make a mapping for `Ctrl ^`. I use double leader (and my leader key is ","), which is very natural and I highly recommend it:

```vim
nmap <leader><leader> <C-^>
```

Theoretically I could add a mapping for `Ctrl ^` in `test.vim`, but when you think about it it wouldn't make much sense, because it's not test-related (it just switches to the alternate buffer), and it's better that every user sets its own preferred mapping.

**Comment by lee-kagiso** [comment]
Thanks, that is a good idea!
