### ISSUE TITLE
Php behat not working

### ISSUE THREAD

**Issue by haringsrob** [janko-m/vim-test#231]
Hi,

For some reason it seems to not pick up php behat files. In my project when running tests it tries to execute cucumber.

I tried debugging setting:
let g:test#ruby#cucumber#file_pattern = '\.rbyfeature$'

so that it would no longer match and fall back to php behat, but now it simply says it cannot find a test file.

Any suggestions?

**Comment by janko-m** [comment]
In addition to checking that the file extension is `.feature`, test.vim's behat runner also checks whether there are any PHP files inside the `features/bootstrap/` directory. If there are no PHP files in that directory, then test.vim starts looking for other strategies, because a `.feature` file could also just as well be a Cucumber file.

**Comment by haringsrob** [comment]
My directory structure is as following:

site/
site/vendor
site/tests/behat.yml
site/tests/features/demo.feature
site/tests/features/bootstrap/featurecontext.php

So it might not be able to handle subdirectories?

**Comment by janko-m** [comment]
This detection should work if you’re cd’d into the site/tests/ directory, it has to be your working directory.

If you’re running tests from the directory which holds this tree (level up from the site/ directory), then detection won’t work.

You can fix this by telling test.vim to cd into the site/tests/ directory before running tests, by setting

```vim
let g:test#project_root = “site/tests”
```
