### ISSUE TITLE
Elixir ExUnit: Not a Test File

### ISSUE THREAD

**Issue by randre03** [janko-m/vim-test#246]
Sorry in advance, I know you receive these questions all of the time, but I simply cannot figure out how to get vim-test to run my test suite when I run the command in a buffer that is not a test file. I am using Elixir and ExUnit. All my tests are in the following format (is this the correct regex???):
` let test#elixir#exunit#file_pattern = '*_test\.exs'`

I am using vim-rooter[https://github.com/airblade/vim-rooter](url) so that I can make fzf search in my project root (and not just the pwd). I thought it might be interfering with vim-test's need to know the pwd, but I removed it and still had the issue.

Thanks in advance - vim-test really is fantastic!

**Comment by codeinabox** [comment]
What is the name of the file you are trying to run tests for?

**Comment by randre03** [comment]
That would help, wouldn’t it?

`physics_test.exs`

- Roger

On Nov 12, 2017, 9:36 AM -0500, Mathew Attlee <notifications@github.com>, wrote:

What is the name of the file you are trying to run tests for?

**Comment by codeinabox** [comment]
That should work. Are you running `TestFile` when that has focus on the buffer, or are you trying to run it from `physics.exs`. If the latter you need to set up projectionist alternate mappings, I've added this to the documentation #247

**Comment by janko-m** [comment]
Note that vim-test uses regexes, not globs, so `'*_test\.exs'` won't work because that's not a valid regex, you would need to use `'.*_test\.exs'`. Also, note that by default vim-test uses its own regex mechanism which is similar but in many cases different than the POSIX standard, the POSIX standard can be turned on via `\v`. Note that the pattern also doesn't have to match the entire file, so you can remove the `.*`, and you should also anchor the end. With all this in mind, the following should work:

```vim
let test#elixir#exunit#file_pattern = '\v_test\.exs$'
```

**Comment by codeinabox** [comment]
@janko-m should we update the default pattern? I assumed it was fine because it passes the specs

**Comment by janko-m** [comment]
@codeinabox Yes, I think we should add `\v` to all patterns, because I cannot think of any reason we would want the regexes to behave in the way we're all used to 😃

**Comment by janko-m** [comment]
@codeinabox Node that in Vim regexes, characters `.` and `$` still behave the same as in POSIX regexes, so that's why it works. But for example `(` characters are taken literally in Vim regexes, while `\(` would be the special character which creates a regex group; in POSIX standard it's the opposite.

**Comment by codeinabox** [comment]
This should now be addressed in master with #248
