### ISSUE TITLE
Allow for dynamically setting the working directory for the checker

### ISSUE THREAD

**Issue by aignas** [janko-m/vim-test#250]
This is required for the new `dotnet-xunit` checker that is being introduced with the #249. The idea is that the `dotnet xunit` command needs to be executed from the same folder as the `.csproj` file of the project. However, the global project folder cannot be set dynamically, because the hook to change the directory is executed to early. This may change if #242 or #241 is merged and then we could dynamically detect the project directory.

The function `function! test#csharp#xunit#build_position(type, position) abort` could then be modified to have:

```
    let file = a:position['file']
    let project_path = test#csharp#get_project_path(file)
    let g:test#project_root = fnamemodify(project_path, ':p:h')
```

Note from a comment in the code that has now been removed:
> TODO: if we can hook into the before_run function, then in theory we could set the project_root dynamically before each run, which would remove the necessity of setting the g:test#project_root manually.

At the moment the workaround to get the runner functioning properly with the `autochdir` option enabled is to set the `g:test#project_root` manually.

**Comment by janko-m** [comment]
Thank you for a good explanation of the issue.

I'm not sure whether it would be a good idea for a test runner to modify global variables on the run. The reason why `g:test#project_root` is set before the runner is evaluated is because many runners reference files in generated test commands using relative file paths, and if the directory would change before the generated test command executes, the relative file paths would become invalid.

What do you think about modifying `test#csharp#xunit#build_args(args)` to add a `cd` command to the `.csproj` directory?

**Comment by aignas** [comment]
I agree with modifying the global variables. And now re-thinking it again, the previous solution was ugly as hell.

`cd` in the building of the command may work. I'll test it later. :)

**Comment by janko-m** [comment]
From your description, adding `cd dir/to/.csproj` to the `xunit` test command should have the correct behaviour, so I'm closing this for now.
