### ISSUE TITLE
Sometimes virtualenv is lost when using dispatch

### ISSUE THREAD

**Issue by dustinfarris** [janko-m/vim-test#26]
It happens randomly: sometime when running a test (using dispatch) the new tmux pane will "forget" that it is in a virtualenv, and the test cannot run.  Once I get in this state, the only to get things back to normal is to restart vi.

**Comment by janko-m** [comment]
Hmm, if the new tmux pane sometimes forgets that it's in virtualenv, I'm afraid there is not much I can do, since I'm only building commands that should work in the shell. Is there some command which you can run before the test command to remind the shell about virutalenv?

In general I think it's better that you report it to Dispatch.vim. Or first, when the shell "forgets", try to open a new tmux pane manually and run the test command. If the command works (but doesn't work when Dispatch.vim opens it), then file a bug in Dispatch.vim. Otherwise it may be a bug in tmux, but I don't know how virtualenv works.

**Comment by dustinfarris** [comment]
Thanks for the quick response.  I dug a little deeper, and it's actually not my virtualenv that's missing, but my PYTHONPATH—or at least my additions to it.  The project is a little unorthodox when it comes to this, but effectively pytest is sometimes trying to load my Django settings before injecting the path, sometimes the other way around.  It is really bizarre behavior, but I don't believe it is a bug with vim-test or with Dispatch.

I believe I can solve this by explicitly adding the missing PYTHONPATH directories to my virtualenv (as opposed to appending them on the fly at runtime).
