### ISSUE TITLE
Vimux strategy and "window" mode: Operators just paste command into buffer

### ISSUE THREAD

**Issue by adc17** [janko-m/vim-test#266]
I'm using neovim v0.2.2 with the following config:
```
let g:VimuxRunnerType = "window"
let test#strategy = 'vimux'
let test#javascript#jasmine#file_pattern = '\.test\.js'
```
I have vim-test and vimux installed via vim-plug. 

Whenever I try to run a vim-test command, a line is pasted into my buffer (it looks like the CLI command).

e.g., for `:TestFile` in `users.test.js`, I get the following:
```
ear; echo -e 'node_modules/.bin/jasmine spec/controllers/users.test.js'; node_modules/.bin/jasmine spec/controllers/users.test.js
```

If I remove `let g:VimuxRunnerType = "window"`, the behaviour goes away.

**Comment by janko-m** [comment]
@adc17 I'm not able to reproduce this behaviour 😕

Which versions of tmux and Vimux are you using? I'm on tmux 2.0 and latest version of Vimux. Note that all test.vim is doing is `call VimuxRunCommand('test command')`, so if there is any bug, it's most likely in Vimux itself. You could easily rule test.vim out by running the Vimux function directly.

Note that I did get this behaviour before I set `let g:VimuxUseNearest = 0`, because Vimux would try to execute the test in the nearest pane which ran Neovim, as it didn't detect that Neovim is also a Vim session.

**Comment by adc17** [comment]
@janko-m the `let g:VimuxUseNearest = 0` setting fixes this for me too. 

n.b. I couldn't test out `call VimuxRunCommand('...')`—vimux reported that the params I'd provided weren't valid—but I think you've identified the issue.
