### ISSUE TITLE
Not a test file

### ISSUE THREAD

**Issue by nihlaeth** [janko-m/vim-test#27]
I've been trying to get vim-test v1.2.0 working with python and nosetests under linux (Slackware 14.1), but all I get is "Not a test file" when running any of the :Test* commands, regardless of the current buffer.

Running :Nose directly works fine.

**Comment by janko-m** [comment]
Does the filename of your test file conform to the "test_*.py" format (e.g. test_foo.py)? Can you give me one test filename which test.vim doesn't recognize as a test file? When your current buffer is on the test file, what output does the following Vim command give you:

```vim
:echo fnamemodify(expand('%'), ':t') =~# '^test_.*\.py$'
```

**Comment by nihlaeth** [comment]
Well, no, as nosetests recognizes test.* as tests files too, I assumed vim.test would as well (finding no documentation to cobradict that). I'll just modify the regex then, thanks!

**Comment by janko-m** [comment]
You know nosetests better than me, I thought that it supported only `test_*.py` files. If it supports other filenames as well, I want to support it to :)

Can you point me to some docs about this, if you know of any? What kind of filenames are `test.*`, is there something after the dot that isn't `.py`?

**Comment by nihlaeth** [comment]
According "man nosetests", the default matching pattern is (?:^|[b_.-])[Tt]est)

That doesn't mention the ending/file extension because it probably does not look at files, but at modules that can be imported from within python. You're probably safe if you go for (?:^|[b_.-])[Tt]est).*\.py as match.

**Comment by nihlaeth** [comment]
As an afterthought, nose will try to find tests in any file you feed it. The matching is only used if you don't specify any. Is there a reason why you want to do your own matching here?

Personally, I have some tests I do NOT want executed when running the whole suite, as they do extensive profiling, or take a long time for testing performance and stuff. I usually just give those a name that does not get through nose's matching, but I might want to run them with vim.test. Nose does some matching in function/class/method naming as well, so you're pretty safe, throwing any .py file at it.

**Comment by janko-m** [comment]
The reason why I do pattern matching in general is because test.vim works in a way that it tries to recognize which file is a test, and which is application code. And when you're in an application file and you run your tests, test.vim runs the tests from the last test file. This very useful when you're trying to make your tests pass, that you don't have to always switch to the test file to run tests.

For that reason I need to be able to recognize between the two.

**Comment by janko-m** [comment]
I pushed now a fix with a looser pattern for Nose's test files (I took your recommendation slightly simplified).

Is there any other way to filter out some test's from the test suite? Because naming files in a way that generic Nose's regex won't match it doesn't seem like an ideal way. I guess another way would be to put slower tests in another directory, and then you could hopefully run something like `:Nose test/fast` and `:Nose test/slow`. I know it's not ideal, but I currently don't see a better solution. Do you have an idea?

**Comment by nihlaeth** [comment]
Nosetests has some command line handles to exclude certain tests, I could just use those.

The looser pattern works, by the way. Thanks for fixing this :)

**Comment by janko-m** [comment]
No problem, thanks for reporting :)

Test.vim supports CLI options, so if you usually want to run the test suite *without* the slow tests, you could add a default option in your `.vimrc`:

```vim
let test#python#nose#options = {'suite': '<options>'}
```

These options will be included on each `:TestSuite` (whatever you mapped it to).

**Comment by firedev** [comment]
How do I make it so it runs rspec suite without having a spec file opened?

**Comment by kagux** [comment]
@firedev I don't think that's possible unless there was an option to set default tests runner. Otherwise, how would the plugin know what to run?

**Comment by janko-m** [comment]
@firedev Like @kagux said, vim-test can't know which test runner to run without a prior context (context being that you opened a test file and ran a test through vim-test). But you can always explicitly call the test runner command by executing `:RSpec` inside of Vim.

**Comment by firedev** [comment]
I see, thanks. That's kind of what I did.

**Comment by anhari** [comment]
@janko-m is there a way to set the test runner to rails by default when in a rails directory?  Sometimes I want to use `:TestSuite` without having been in a spec file yet.

**Comment by janko-m** [comment]
@anhari Not yet, there is already https://github.com/janko-m/vim-test/issues/147 for this idea.

**Comment by anhari** [comment]
@janko-m subscribed, thanks man.  Appreciate all of your hard work on this.
