### ISSUE TITLE
Readme suggestion for setting `test#runners` isn't reload safe

### ISSUE THREAD

**Issue by jfly** [janko-m/vim-test#306]
I added a custom test runner as per the instructions here: https://github.com/janko-m/vim-test#extending.

This works, but if I ever reload my vimrc, then when I try to use vim-test, I get scary errors like this:

```vim
Error detected while processing function test#run[18]..test#base#build_position:
line    1:
E117: Unknown function: test#0#build_position
E15: Invalid expression: test#{a:runner}#build_position(a:type, a:position)
Press ENTER or type command to continue
```

I was able to work around this by only setting `test#runners` if it is not already set, but that doesn't feel like the best solution to me:

```vim
if !exists("test#runners")
    let test#runners = {'HonorJs': ['HonorRunner']}
endif
```

**Comment by janko-m** [comment]
Hmm, yeah, that's definitely a bug. The problem is that the same `test#runners` variable gets extended when loading the plugin with all the other test runners. But it's obviously wrong to use the same `test#runners` variable, it would be better to use something like `test#custom_runners`. I'll make that change.

**Comment by AckslD** [comment]
@janko was this bug fixed? I get the same error when simply setting `test#python#runner = 'pytest'` and running the tests by for example `TestFile`.
