### ISSUE TITLE
Jest errorformat?

### ISSUE THREAD

**Issue by olalonde** [janko-m/vim-test#331]
So I'm using [Jest](https://github.com/facebook/jest) with the `dispatch` strategy. It works but the quickfix window seems to get populated with the whole console output of the jest test. For example:

```
|| Determining test suites to run...[999D
|| [1A
||  RUNS  src/graphql/query.test.js
|| [1A FAIL  src/graphql/query.test.js
|| 
||  RUNS  src/graphql/query.test.js
|| [1A  ✕ root graphql query (9ms)
|| 
||  RUNS  src/graphql/query.test.js
|| [1A  ✕ query { me { username } } (15ms)
|| 
||  RUNS  src/graphql/query.test.js
|| [1A  ✓ query { me { username } } (unauthenticated) (14ms)
|| 
||  RUNS  src/graphql/query.test.js
|| [1A  ✕ erroformat (1ms)
|| 
||  RUNS  src/graphql/query.test.js
|| [1A
|| 
||  RUNS  src/graphql/query.test.js
|| [1A  ● root graphql query
|| 
||     yay
|| 
||       12 | // Run the GraphQL query '{ hello }' and print out the response
||       13 | test('root graphql query', async () => {
||     > 14 |   throw Error('yay');
||          |         ^
||       15 |   const r = await g('query { hello }');
||       16 |   expect(r.data).toEqual({ hello: 'Hello world!' });
||       17 | });
|| 
||       at Object.Error (src/graphql/query.test.js:14:9)
|| 
||   ● query { me { username } }
|| 
||     test123
|| 
||        95 |   validate(schemas.user, args => args.user),
||        96 |   async ({ user: { username, password = null } }, { store, jwtHelper }) => {
||     >  97 |     throw new Error('test123');
||           |           ^
||        98 |     if (selectors.userByUsername(store.getState(), username)) {
||        99 |       throw new UsernameAlreadyTakenError();
||       100 |     }
|| 
||       at Object.<anonymous>.createUser (src/model/commands.js:97:11)
||       at Object.fn [as createUser] (src/model/utils.js:27:20)
|| 
||   ● erroformat
|| 
||     expect(received).toBeFalsy()
|| 
||     Received: true
|| 
||       41 | 
||       42 | test('erroformat', () => {
||     > 43 |   expect(true).toBeFalsy();
||          |                ^
||       44 | });
||       45 | 
|| 
||       at Object.toBeFalsy (src/graphql/query.test.js:43:16)
|| 
|| 
||  RUNS  src/graphql/query.test.js
|| [1A
||  RUNS  src/graphql/query.test.js
|| [1A[999DTest Suites: 1 failed, 1 total
|| Tests:       3 failed, 1 passed, 4 total
|| Snapshots:   1 passed, 1 total
|| Time:        1.057s, estimated 2s
|| Ran all test suites matching /src\/graphql\/query.test.js/i.

```

I tried for two hours to get this to work and I now give up. Hoping someone can help.

**Comment by janko-m** [comment]
vim-dispatch works in a way that it activates the appropriate vim compiler according to the test command, and that compiler in turn sets the `errorformat`. Since `dispatch` is just one of the vim-test's strategies, many of which don't work with vim compilers, it's not in scope of vim-test to provide compilers for test runners.

A quick search on GitHub found https://github.com/craigdallimore/vim-jest-cli, which provides a compiler for jest, but for some reason matches on `jest-cli` instead of `jest`. I think the following vim-dispatch configuration should make sure that the `jest-cli` compiler will get activated on `jest` commands:

```rb
let g:dispatch_compilers = { 'jest': 'jest-cli' }
```

**Comment by olalonde** [comment]
Thanks. I managed to get a cleaner test output using https://github.com/olalonde/vim-test-jest-clean-qf-reporter/tree/parse-error : 

Is there a function from this plugin I can use to detect if it plans to use Jest so that I can conditionally set the error format? In pseudo code:

```
if vimtest.hasDetected('jest')
  set efm=%.%#\ at\ %f:%l:%c,%.%#\ at\ %.%#(%f:%l:%c)
endif
```

**Comment by olalonde** [comment]
Oh never mind, I just realized I should just append to errorformat with `+=`.

**Comment by janko-m** [comment]
You can create a compiler file and put it under `compilers/` inside your `~/.vim` folder with the following content:

```
" ~/.vim/compilers/jest.vim
if exists("current_compiler")
  finish
endif
let current_compiler = "jest"

if exists(":CompilerSet") != 2		" older Vim always used :setlocal
  command -nargs=* CompilerSet setlocal <args>
endif

let s:cpo_save = &cpo
set cpo-=C

CompilerSet makeprg=jest
CompilerSet errorformat=%.%#\ at\ %f:%l:%c,%.%#\ at\ %.%#(%f:%l:%c)

let &cpo = s:cpo_save
unlet s:cpo_save
```

vim-dispatch matches the test command prefix onto `makeprg` for each compiler, and as soon as it finds one that matches, it activates it by setting the defined `errorformat` (and then reverts back to the previous `errorformat` after the test command finishes, so that it doesn't create side effects). I haven't tested whether it works, but I think it should.

**Comment by olalonde** [comment]
Thanks @janko-m 

I ended up writing this jest reporter which outputs logs that vim can understand: https://github.com/olalonde/jest-quickfix-reporter
