### ISSUE TITLE
How can i close the test window and make the cursor go back to the place before running tests

### ISSUE THREAD

**Issue by zhaochy1990** [janko-m/vim-test#338]
I'm using neovim, and the strategy 'neovim'.

If I only have one window, after I run some test, and close the test result window, the cursor goes back to the place before I run the test.

If I have several windows open at the same time. And I run some test, and don't scroll at the test window. The cursor goes back again.

But,
If I have several windows open at the same time. And I run some test, and **scroll at the test window**.
The cursor goes to the most left window when I close the test window.

**scroll at the test window** breaks the behavior of moving cursor back to the place before running the test.

I'm not sure if this is a bug or by the behavior of neovim terminal.... Can some experts have a look at this?

**Comment by janko-m** [comment]
The `neovim` strategy does its best to go back to the previous window, I didn't know that scrolling breaks it. This is the whole code of the `neovim` strategy: https://github.com/janko-m/vim-test/blob/9ebecb9d1a53c7cfa646e49066ecb91a78b42ba6/autoload/test/strategy.vim#L51-L57

I'm not a (Neo)Vim expert, so If anyone finds out how to achieve the correct behaviour when scrolling, I'll happily merge the patch in.

**Comment by elythyr** [comment]
Hi,

I had never experienced that so I tried a few  things and I finally managed to reproduce it.
If I'm not mistaken, that's the scenario you are talking about:
```Gherkin
Given you have two windows opened in vertical split
And you cursor is in the "right window"
When you launch a test
And press "Escape" to go back to normal mode
And you type ":q" to close the window
Then your cursor is in the "left window"
```

If that's it then, just type press `a` two times.
The goal is to press a to "append" and go back into insert mode, then press any key to close the window.

The reason is that closing a window doesn't trigger the `BufDelete` event, therefore the auto command on line 55 (previous response) is not activated.
If you try to type `:bd!` instead of `:q` it will work ;)

If it's really important for you to be able to close the window manually, then you will have to try to add a new auto command or change the event used, maybe BufWinLeave ?
But honestly, pressing `aa` is so quick, you don't even have to move your hands, it seems a bit overkill :)

**Comment by zhaochy1990** [comment]
It works, thank you.

`aa` is good, and quick, and comfort, so, thank you !

**Comment by zhaochy1990** [comment]
And a suggestion is, can we make the scroll a default behavior?

Usually we need to scroll up and down at the test window to verify the test results, console output, etc.
It would be more convenient to enable the scroll by default (or have an option to make it configurable).

**Comment by janko-m** [comment]
That's my preference as well. The README shows how you can map `Ctrl-o` to leave the insert mode (for me `Escape` didn't work for some reason), so that afterwards you can scroll.

But maybe we can do a compromise. As far as I know, the most common key to press when you're greeted with a "press any key to continue" message is `Enter`. So maybe we can keep the insert mode, but map `Enter` (which AFAIK is not used for anything) to exit the terminal, and show a "Press <Enter> to exit the terminal". A similar [PR](https://github.com/janko-m/vim-test/pull/342) for Vim 8 terminal strategy was merged recently.

**Comment by zhaochy1990** [comment]
Thanks, close this issue.
