### ISSUE TITLE
Reversing command-line argument order?

### ISSUE THREAD

**Issue by kevinburkeshyp** [janko-m/vim-test#36]
Hi, I'm trying to pass vim-test's arguments to a Go program... which can only parse positional arguments after all keyword arguments have been passed. Eg this is fine...

```
myprogram.go --grep foo test/lib/client.test.js
```

However, Go's `flag` package ignores the --grep arguments here...

```
myprogram.go test/lib/client.test.js --grep foo
```

I tried editing `test#javascript#mocha#build_position` to change the order, like this:

```vim
function! test#javascript#mocha#build_position(type, position) abort
  if a:type == 'nearest'
    let name = s:nearest_test(a:position)
    if !empty(name) | let name = '--grep '.shellescape(name, 1) | endif
    return [name, a:position['file']] " Reversed order here.
  elseif a:type == 'file'
    return [a:position['file']]
  else
    return []
  endif
endfunction
```

However I get the following error: `Invalid expression: s:nearest_test(a:position)`.

Any ideas about how I can get a Go-compliant argument order? FWIW Mocha doesn't care which order the arguments go in...

**Comment by janko-m** [comment]
Thanks for reporting this. I think in general it makes sense to order the cli arguments in the way you described, so if I change it globally, I think every other test runner should still work properly. I will work on this.

**Comment by janko-m** [comment]
I'm actually not really sure what you're trying to do. Could you specify exactly what you want test.vim to do?

Because there are currently two ways of passing command-line arguments: directly in the Vim command (:GoTest --grep foo) or by setting a global Vim variable specific to the test runner. However, both of these are putting those CLI arguments in the beginning (like you want).

Why were you modifying the Mocha wrapper? Do you want me to change that one?

**Comment by janko-m** [comment]
Have you figured out the solution?

**Comment by janko-m** [comment]
Ok, I will close this, reopen it if you're still having some problems.

**Comment by kevinburkeshyp** [comment]
Sorry... need to dig into this a little more to get you a good answer, and haven't had time :(

**Comment by kevinburkeshyp** [comment]
Will post more details if/when I do that
