### ISSUE TITLE
Slow with Clojure

### ISSUE THREAD

**Issue by lee-kagiso** [janko-m/vim-test#38]
Running Clojure tests is quite slow. Much slower than running py.test tests, which run immediately.
It can easily take several seconds to start running a test. I am using vim fireplace.

To replicate:
```lein new compojure slowtest```
and run the sample test there.

**Comment by janko-m** [comment]
Hmm, that is strange, because I'm running tests in the same way vim-fireplace does, and it worked fast for me when I was testing it. Now the terminal is breaking for me for some reason when I try to run tests, but I can't debug it because I don't really know Clojure :)

Anyway, the reason the tests are slow is most probably because vim-fireplace is starting the REPL before each test. I think it says in the documentation that vim-fireplace should start the REPL once in the background, and then automatically reuse it later, so that you get fast tests.

Try running vim-fireplace's `:RunTests` or `:RunAllTests`, if those are slow as well, then the problem is somewhere in vim-fireplace, that it's not able to resuse an existing REPL (which is something I cannot solve in vim-test).

**Comment by leebrooks0** [comment]
```:RunAllTests``` runs instantly after the first run, but ```:TestNearest``` is taking roughly 3 seconds each time.

**Comment by janko-m** [comment]
@leebrooks0 What about `:TestSuite`?

**Comment by leebrooks0** [comment]
```:TestSuite``` runs instantly

**Comment by leebrooks0** [comment]
and ```:TestFile``` is slow

**Comment by janko-m** [comment]
@leebrooks0 Thanks a lot for raising the issue on Fireplace.vim, I only saw the reference now. Tim Pope closed the issue with https://github.com/tpope/vim-fireplace/commit/459904381bc7dcb295b48fd7bcfa23a134293eca, where he implemented the `:.RunTests` command for running nearest tests. This allowed me to reimplement the Clojure support only by using Fireplace.vim's high-level commands, and drop all the complicated logic that was needed to reimplement those commands.

Now Test.vim delegates directly to Fireplace.vim, so if there is any more slowness, it should be solved Fireplace.vim itself.

Currently `:TestSuite` doesn't work because of a bug in Fireplace.vim, but I made a PR https://github.com/tpope/vim-fireplace/pull/236, so hopefully it will get merged soon.

The only issue that can hurt the worflow a bit is when running the last nearest test. Fireplace.vim's `:.RunTests` only works when when you run it inside a test file, which means that if you're in another file and you run `:TestNearest`, Test.vim first has to switch to your test file in order to run the nearest test. If you have `cmdheight` set to 1 (which is the most common setting), this will cause a "Press ENTER or type command to continue" prompt. I didn't see a general way to work around this, but users can see `:help hit-enter` for more explanation and find a workround if they really need it.
