### ISSUE TITLE
Javascript / mocha: Not a test file

### ISSUE THREAD

**Issue by ArjanFrans** [janko-m/vim-test#40]
My tests files are not recognized when running any of the commands (:TestNearest, :TestFile, etc.). They all report 'Not a test file'. My test files are in the 'test' directory. The :Mocha command itself does work.

**Comment by janko-m** [comment]
Do your test files satisfy the regex `tests?/.*\.(js|coffee)$`? This is what test.vim currently uses for recognizing the test files for Mocha. Open the test file in the buffer, and check if

```
:echo expand('%') =~ '\vtests?/.*\.(js|coffee)$'
```

returns `1`. If it returns zero, then something is strange (because this regex recognizes any `.js`/`.coffee` file in the `test/` directory).

**Comment by ArjanFrans** [comment]
It returns 0.

My directory structure is basically like this, the Node convention:
```
/lib
--code.js
/test
--index.js
```
I open vim in the root, then open test/index.js.

**Comment by janko-m** [comment]
I cannot seem to reproduce, for me the following works:

```
mkdir myproject
cd myproject
mkdir test
touch test/index.js
vim test/index.js
:TestFile
```

**Comment by ArjanFrans** [comment]
Strange... I also did exactly the same thing you did. Still 'Not a test file'.

**Comment by janko-m** [comment]
Are you using the latest version of vim-test?

**Comment by ArjanFrans** [comment]
Yes, I cloned the repo. It's weird that the regex returns 0, since that should be unrelated to the plugin.

**Comment by janko-m** [comment]
You're right, that is unrelated. Could you try testing the regex without the `.vimrc` or any plugins, starting up Vim with `vim -u NONE test/index.js`?

**Comment by ArjanFrans** [comment]
It returns 1. I guess I have some conflicting plugins or settings.

**Comment by ArjanFrans** [comment]
It turns out that the following setting broke the regex: `set autochdir`

**Comment by janko-m** [comment]
Ah, yeah, this definitely breaks vim-test, because it has to know in which folder are your files located.

**Comment by fortes** [comment]
I'm a big fan of `autochdir`, but would still like to use `vim-test`. Is it possible to test against the full file path?

**Comment by janko-m** [comment]
The thing is, test.vim relies on the fact that your working directory is the root of your project. This way it knows whether a file is a test file or production file. If I would expand the file path to the full pathname, then I wouldn't know which is the actual subfolder of the project `test/`, and it could theoretically happen that your project is located in a `test/` folder (although I know, very unlikely).

This is also how it knows where to find things like `node_modules` or other files in other testing frameworks, in order to do some smart decisions. That means that for every file test.vim would have to traverse up the file hierarchy until it finds a wanted file or until it reaches the root directory of your disk. This sounds very inefficient to me, and would complicate code in each place I check something in the filesystem.

**Comment by fortes** [comment]
Not sure if it could be leveraged here, but I use the Project Root plugin ( https://github.com/dbakker/vim-projectroot ) in order to run some commands (like grepping, etc) from the root of any project.

Another option would be to allow for customizing the test -- in the project I'm currently working on, all test files end with `_test.js`, which would be easy to match if an appropriate property were exposed.

**Comment by janko-m** [comment]
I agree with your latter suggestion, the users indeed should be able to change the test file regexes, I opened a separate issue for it. I will fix it sometime in the next two weeks.
