### ISSUE TITLE
Support for shoulda-context

### ISSUE THREAD

**Issue by cseelus** [janko-m/vim-test#44]
Great/superclean wrapper. 

Any chance of adding support for the quite popular [shoulda-context](https://github.com/thoughtbot/shoulda-context) context framework (`TestNearest`, rest works), which is quite popular amongst Rails devs?

**Comment by janko-m** [comment]
I investigated shoulda-context, but for some reason it produces too unpredictable method names. The following:

```rb
require "minitest/autorun"
require "shoulda-context"

class CalculatorTest < Minitest::Test
  should "be shiny" do
    # ...
  end

  context "addition" do
    should "be possible" do
      # ...
    end
  end
end
```

produces methods that are equivalent of the following:

```rb
require "minitest/autorun"

class CalculatorTest < Minitest::Test
  define_method('test_: addition should be possible.') do
    # ...
  end

  define_method('test_: Calculator should be shiny.') do
    # ...
  end
end
```

These are actual methods in quotes, I just needed to use `define_method` because they contain a `:` and a `.`. Notice in the second method how it transformed "CalculatorTest" into "Calculator".

So, because of that, I cannot construct reliable regexes. I honestly don't know what people see in shoulda-context, its functionality is already supported by minitest/spec.

**Comment by cseelus** [comment]
Glad we had the same results regarding method names.

Its the difference between …

![screen shot 2015-07-31 at 6 59 39](https://cloud.githubusercontent.com/assets/3188392/9001055/d405efda-3751-11e5-8df4-bbeb1fb9ae97.png)

… which becomes hard to read soon, an this …

![screen shot 2015-07-31 at 6 59 58](https://cloud.githubusercontent.com/assets/3188392/9001058/e2bd9672-3751-11e5-933a-24699d20ef3b.png)

… which really makes a difference in more sophisticated tests with different contexts, regarding readability etc. and I guess its what makes people use *shoulda context*.

But thanks for the immediate try, thats really appreciated.

**Comment by janko-m** [comment]
But isn't shoulda-context reimplementing minitest/spec? I get that with test/unit (before minitest) it was really useful, but minitest has minitest/spec, which does the same thing, but much more transparent, so test.vim supports it.

**Comment by cseelus** [comment]
No, not really, it just adds some [context and should blocks](https://github.com/thoughtbot/shoulda-context#contexts) while it allows you to stick with your good old minitest syntax.

Using minitest/spec is a matter of taste, [a](https://blog.engineyard.com/2014/seven-reasons-i-love-minitest) [couple](http://blog.plataformatec.com.br/2015/05/nobody-told-me-minitest-was-this-fun/?utm_content=buffer3c562&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer) of Minitest users prefer to avoid the specification style and instead use minitest/test, as it's closer to the metal and uses a more vanilla Ruby syntax.

**Comment by janko-m** [comment]
That's exactly the part I don't get :). If someone uses minitest/spec, then they don't need shoulda-context, since minitest/spec already provides that syntax. On the other hand, I prefer the minitest/test syntax, because I like the explicitness of it. But then again why would I ruin it by adding shoulda-context? So why would I ever use it? :)
