### ISSUE TITLE
Minitest::Spec detected as RSpec

### ISSUE THREAD

**Issue by kdisneur** [janko-m/vim-test#48]
Hi,

I'm working on a ruby project where files are named `_spec.rb` but they are not RSpec files, they are Minitest::Spec files. 

To have my test working, I tried to override `tests#runners` in order to to define Minitest as the only Ruby runner available. Unfortunately it  was not working because `vim-test` override what I set with its own default values (https://github.com/janko-m/vim-test/blob/c70614e1b7c8d8d7a8008ce3c93e202b2ff497f1/plugin/test.vim#L14..L26). 

I'm wondering why `test#runners` is overridden with default values? Shouldn't it be the inverse: default overridden by specific?

Maybe there is a better way to achieve what I try to do?

Thank you for your help

**Comment by janko-m** [comment]
Yes, that was my endless dilemma: if the file ends with `_spec.rb`, then I don't know if it's RSpec or Minitest. If everyone used the "no monkeypatch" style in RSpec (`RSpec.describe`), then I could just detect "RSpec" in the file, and then I would know. But I don't know how many people switched, so this file could be both RSpec and Minitest:

```rb
require "spec_helper"

describe "Foo" do
  # ...
end
```

With the lack of a robust way to detect one of these two, I decided to prefer RSpec, since Minitest users can always just rename their `_spec.rb` files to `_test.rb`, and problem solved. Even though I strongly consider that Minitest files should be named `_test.rb`, I know I shouldn't dictate how Minitest users should name their files, but I didn't find another solution.

The `test#runners` are overriden in this way, because `s:extend` doesn't do an actual `Hash#merge!`, it merges arrays of existing keys, so there is no way to override the array. But I thought of another solution now. When I solve #41, and switch the order of Minitest and RSpec so that Minitest is first, then you could override the file regex for Minitest to `_spec.rb$`.

**Comment by kdisneur** [comment]
Thanks for the reply. 

I understand the problem and I'm totally agree with you `_spec.rb` is mainly rspec users.

I never used vimscript a lot so I didn't know the behaviour of `s:extend`, I thought it the same as a merge. Shame.

So I guess you can close this issue because, as you said, it will be fixed with #41. 

It looks a small feature to implement, even for a beginner, except if I missed something. Have you already started to tackle this issue or are you opened for a contribution?

**Comment by janko-m** [comment]
I needed to implement `s:extend` in that way so you can add additional testing frameworks without overriding existing ones.

I will leave this issue opened, since I still need to change the order of Minitest and RSpec in `test#runners` :). #41 is open for contribution, I intended to tackle it after I fix one other issue now, but if you want, you can work on it. Basically you just have the default regex in the variable.

**Comment by janko-m** [comment]
https://github.com/janko-m/vim-test#file-pattern

**Comment by kdisneur** [comment]
Thank you very much for the feature! :smile_cat:
