### ISSUE TITLE
Cannot find module 'coffee-script/register'

### ISSUE THREAD

**Issue by wayneashleyberry** [janko-m/vim-test#52]
I got the following error while attempting to use vim-test on the following file:

https://github.com/wayneashleyberry/phplint/blob/master/test/test.js

```
:!node_modules/.bin/mocha --compilers coffee:coffee-script/register test/test.js
module.js:338
    throw err;
          ^
Error: Cannot find module 'coffee-script/register'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/Wayne/source/phplint/node_modules/mocha/bin/_mocha:300:3
    at Array.forEach (native)
    at Object.<anonymous> (/Users/Wayne/source/phplint/node_modules/mocha/bin/_mocha:294:19)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

shell returned 1
Press ENTER or type command to continue
```

**Comment by antonklava** [comment]
I believe I have a similar issue.

Currently `vim-test` crashes [on this line](https://github.com/janko-m/vim-test/blob/master/autoload/test/javascript/mocha.vim#L61) for me. Because it's trying to find my current coffee-script version, but I do not use coffee-script nor have it installed.

I think it comes down to a few lines above how the test for coffee-script files is done with `glob('**/*.coffee')` – some modules in my _node_modules_ folder includes `.coffee` files that trigger the coffee-script compiler settings.

One solution could be to look at the filename for a `.coffee` ending instead of globbing.

**Comment by antonklava** [comment]
@wayneashleyberry a temporary solution that worked for me was adding this to my `.vimrc`

```
function! test#javascript#mocha#build_args(args) abort
  return a:args
endfunction
```

**Comment by janko-m** [comment]
Someone needs to clarify this for me. If you have a CoffeeScript file in node_modules/, don't you still need a CoffeeScript compiler to use that module? Maybe I can exclude the node_modules/ directory.

I was thinking of looking at the test filename for a .coffee ending, but I thought that someone might have production code in CoffeeScript, while still prefering to write tests in JavaScript.

**Comment by antonklava** [comment]
Excluding _node_modules_ directory will probably solve this. I do not know of any libraries that require you to include .coffee files directly.

In my case I had files like [js-tokens/regex.coffee](https://github.com/lydell/js-tokens/blob/master/regex.coffee) in the _node_modules_ directory and other files from different test-cases.

@janko-m allowing javascript tests in a coffee-script project is definitely a good feature and should still be possible.

**Comment by janko-m** [comment]
But if you would import that module (which probably happens if it's a dependency), wouldn't you need a CoffeeScript compiler?

**Comment by antonklava** [comment]
I suppose that _can_ happen, but from my understanding it's more common, since coffee-script compiles down to javascript, that libraries ship with the compiled javascript version of their modules. That way people using coffee-script and javascript can use the same library.

There are probably exceptions and a configuration option may be needed to satisfy both.

Another way could be to simply remove coffee-script and jsx options completely from `vim-test` and use `test#javascript#mocha#executable` or [./test/mocha.opts](https://mochajs.org/#mocha-opts) file to set these type of options. Personally I'd go this way since the mocha.opts file is quite flexible.

**Comment by janko-m** [comment]
That sounds like a great solution. I think things like this should be in test/mocha.opts, since that makes tests easier to run on the command-line as well (and I don't have to try being smart :)).

**Comment by antonklava** [comment]
:+1: I can make a try at a PR tonight or tomorrow evening unless you've fixed it by then. Thanks for `vim-test` btw, I use it all day every day.

**Comment by janko-m** [comment]
Thanks for taking the time to work towards a solution! I'm glad you enjoy using vim-test :)
