### ISSUE TITLE
Bug: Django runner incorrectly being selected, causing error

### ISSUE THREAD

**Issue by sloria** [janko-m/vim-test#56]
I am using the latest `master` branch. When running any of the test commands in one my projects, I get the following error:

```
|| /var/folders/kd/9_jv37r94035mc9b94b3f_6c0000gn/T/vBLw9a9/37:56: permission denied: /Users/sloria/projects/flask-projects/manage.py
```

Django is not in my virtualenv and there is no manage.py file, so I'm not sure why the django runner is selected. Even if I set my test runner with:

```
let test#python#runner = 'pytest'
```

The error still happens.

**Comment by janko-m** [comment]
@benjohnson Could you help me with this? It seems that `findfile()` is triggering the permissions error. The reason why you didn't just `glob('**/manage.py')` is because Django projects can have multiple applications, in which is common to `cd` in, so `manage.py` is higher in the directory structure, right? But can the application root be further than 1 folder down? As I see, in common Django directory structure manage.py is usually either in `manage.py` or `../manage.py`, no?

**Comment by benjohnson** [comment]
Yeah. So in Django projects ./manage.py is always in the root directory of the project, but the idea was that your current working directory could be higher up the stack. So, if you're cd'd into myapp/someapp/tests and you run a test, we'd like it to pick up Django. What's worse, we need to know where the manage.py is so we can run tests from there.

Here's a few options off the top of my head:

1) We could just accept as a project constraint that you have to be cd'd into the root directory where manage.py is and avoid findfile() entirely, but I can see that affecting the way a lot of people use vim and Django.

2) We could check for the existence of the `django-admin` executable as a way to tell if we should run the test runner. That way we'd only be calling findfile() to get the path of ./manage.py if you actually have django installed (in the virtualenv).

I think giving (2) a shot is worth it. And if that still doesn't work we could go for (1). We also probably want to consider making sure that `test#python#runner` can skip the Django test entirely.

**Comment by benjohnson** [comment]
[This branch](https://github.com/benjohnson/vim-test/tree/django-executable) has the change to checking for the executable instead of doing `findfile()` in case @sloria wants to give it a shot and see if it fixes his problem.

**Comment by janko-m** [comment]
Test.vim is already built with the constraint of having to be cd'd in the root of the project. When I was building test.vim, I was thinking whether it should have this constraint, and I have found 2 reasons in favour:

* It's much easier to check for existence of files when you know Vim will be in the project root. Without this requirement each Vim runner would have to do complex directory traversal.
* It's possible to detect test files for test frameworks which don't differentiate test files by filename. E.g. in Mocha all test files are located in the "test/" directory in project root, but they don't end with `_test.js`, so if I wasn't in root, I would know from the full path of the file if it was in the test/ directory, because it could theoretically happen that the user put the whole project in a "test/" directory.

For those reasons I vote for (1). I think it's good practice to always be in the project root anyway. Yeah, I agree it would be good to add `test#python#runner` as well.

**Comment by benjohnson** [comment]
Oh, that's great. With that constraint this can actually be a lot simpler/more performant. I'll throw together a branch for you.

**Comment by sloria** [comment]
FWIW, @benjohnson 's `django-executable` branch seems to fix the issue. Thank you both for working on this.

**Comment by janko-m** [comment]
Fixed in https://github.com/janko-m/vim-test/commit/3b3ef4fc4b777afefc218570f99747e294ad969b.
