### ISSUE TITLE
iTerm strategy not working

### ISSUE THREAD

**Issue by tbastos** [janko-m/vim-test#62]
Hi,

I tried to look into the problem but it makes no sense to me...  I have iTerm2 2.9.20150923
vim-test tries to execute the following:
```
:!/Users/tbastos/.dotfiles/vim/bundle/vim-test/bin/osx_iterm 'clear; echo -e '\''busted spec/config_spec.lua'\''; busted spec/config_spec.lua'
/Users/tbastos/.dotfiles/vim/bundle/vim-test/bin/osx_iterm:160:168: script error: Expected end of line but found identifier. (-2741)
```
Does the last error message make any sense? osx_iterm doesn't even have 160 lines...

The `terminal` strategy at least opens the Terminal app, but `iterm` just fails silently.
Meanwhile I'm using `dispatch` as it works properly.

Thanks for the plugin!

**Comment by janko-m** [comment]
Could you try executing a simpler command using the osx_iterm script directly? Just something without quotes, so that we know that escaping isn't the problem.

Another possibility may be that this is a script for an older version of iTerm. RSpec.vim has one for nighly  builds, I intended to integrate it but haven't got to it yet. If the above didn't work, could you try downloading this an executing a simple command with it?

https://github.com/thoughtbot/vim-rspec/blob/master/bin/os_x_iterm2

**Comment by tbastos** [comment]
You nailed it, the problem was the script. RSpec's new script works. Thanks!
