### ISSUE TITLE
Quickfix broken with ruby tests (minitest)

### ISSUE THREAD

**Issue by timonv** [janko-m/vim-test#93]
Love the idea behind this!

When I run ruby minitests over Dispatch via vim-test, I get no highlighting nor autojump to the first error. This is frustrating, as it means I have to scroll manually every time to the first error. However, when I run the test manually `:Dispatch ruby -Itest %` it works fine. Using neovim.

**Comment by timonv** [comment]
For the record, the same setup works fine with elixir

**Comment by janko-m** [comment]
That's strange, when I run `:Dispatch ruby -Itest %` it doesn't jump to the first error for me. Maybe you can see what is the command that vim-test generates, you can see that in the status bar of vim-dispatch's quickfix window. I presume the difference is that vim-test uses `rake test` when it can, and only otherwsie falls back to `ruby -Itest`. Then the `rake.vim` compiler is used instead of the default Vim's (`ruby -Itest` doesn't activate any compiler that comes with Vim), which can make a difference. If you want to use `ruby -Itest`, you can always

```vim
let g:test#ruby#minitest#executable = 'ruby -Itest' # add "bundle exec" if you need to
```

in `.vimrc` that local to your project (`:h 'exrc'`).

**Comment by timonv** [comment]
Hmm that doesn't work as it adds `TEST=%` to that line while it should be `ruby -Itest`. It looks like it prepends it with bundle exec, could that cause this issue? I have no issues with rspec btw.

**Comment by janko-m** [comment]
Aha, I think I know what's the problem. Dispatch.vim is probably looking the string from the beginning, and seeing if it matches an executable in a Vim compiler. Since the `bundle exec` prefix won't match any compiler, it will use the default compiler.

However, you can tell dispatch.vim to ignore `bundle exec` by modifying `g:dispatch_compilers` in your .vimrc:

```vim
let g:dispatch_compilers = {'bundle exec': ''}
```

See `:help g:dispatch_compilers` for more information. It took me a while to understand what it means, but essentially it allows you to map executables to compilers, with empty string being a special case. I have this automatically [set up](https://github.com/tpope/vim-bundler/blob/master/plugin/bundler.vim#L13) by [bundler.vim](https://github.com/tpope/vim-bundler).
