### ISSUE TITLE
Toggling interactive mode in PHPSpec

### ISSUE THREAD

**Issue by codeinabox** [janko-m/vim-test#95]
Now I've started using PHPSpec I've noticed that by default it runs in interactive mode. Is there a way of working out which strategies do and don't support interactive mode? Trying to work out the best way users can decide which mode they want to use

**Comment by janko-m** [comment]
By "interactive" mode you mean that it doesn't exit by itself? If that's the case, I think for vim-test it would be much better if it wasn't interactive by default, and that people can enable it if they want to.

**Comment by codeinabox** [comment]
In interactive mode it can ask for user input, for example [if you run a spec and the class being tested doesn't exist it will ask if you want to create the file](https://phpspec.readthedocs.org/en/latest/cookbook/console.html#run-command).

**Comment by janko-m** [comment]
Aha, I see. Well, instead of checking in the runner if the current strategy is in the list of strategies that can support interactive mode, I think it's much better to just let users choose whether they want the interactive mode, depending on their preferences and if they're using a supportive strategy.

```vim
let test#php#phpspec#options = '--no-code-generation'
```

What do you think?

**Comment by codeinabox** [comment]
I agree
