### ISSUE TITLE
Support for Javascript + "tape"

### ISSUE THREAD

**Issue by bugeats** [janko-m/vim-test#97]
Tape is a minimalistic test runner for Javascript:

https://github.com/substack/tape

As you can see from the above link, it also supports many formatters/reporters. From what I understand of vim-test so far, it looks like you could take your pick from one of those as long as core support for `tape` is added.

**Comment by janko-m** [comment]
This seems like a reasonably popular JS test runner, so it makes sense to include it in vim-test. The only non-trivial part is figuring out how to correctly support formatters, since each one seems to be used a bit differently. I will try to get on it tomorrow.

**Comment by janko-m** [comment]
I haven't found time for integrating tape, but it would be great if someone from tape users could write an integration. I will close this then, as it is not a feature that I have time to implement.

**Comment by bugeats** [comment]
>  it would be great if someone from tape users could write an integration

Isn't that the point of this ticket? I recommend you keep tickets like this open so that people that want to contribute can have a reference.

**Comment by aaalsaleh** [comment]
It is fairly easy to implement tape support, and I've already did it. I even allowed a `#reporter` config to specify one of the custom reporters if needed.

However, it is impossible to differentiate between the different javascript frameworks using just the `#test_file` methods. Both Mocha and Tape can have js files under 'test/tests' directory, and the current design of a mere file pattern check is insufficient to differentiate between the two. I had to check whether `node_modules/.bin/mocah` vs `node_modules/.bin/tape` existed along with the file pattern in order to differentiate between which one to use. For example:
```viml
function! test#javascript#mocha#test_file(file) abort
  return filereadable('node_modules/.bin/mocha') && a:file =~# g:test#javascript#mocha#file_pattern
endfunction
```
and
```viml
function! test#javascript#tape#test_file(file) abort
  return filereadable('node_modules/.bin/tape') && a:file =~# g:test#javascript#tape#file_pattern
endfunction
```
Checking these local binaries is the only way to differentiate between them, otherwise one of them will always take precedence.

**Comment by janko-m** [comment]
Thank you for the investigation. Yes, that's why I made `#test_file` functions, so that in addition to pattern matching you can also inspect the environment for whatever you can find.

I like most your first proposed apporach, where you check for the executables in node_modules. It's great that you also thought of reporters, do you think that you could make the `#reporter` variable accept an array, which allows you to pipe multiple reporters at the end? I saw somewhere that this can be done and is useful. In that case it should probably be named `#reporters`.

**Comment by aaalsaleh** [comment]
@bugeats kindly test the PR with your test files.

**Comment by janko-m** [comment]
Added in #119!
